{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Medidas Instalação\",\"Medidas Onboarding\",\"Medidas\",\"dColaboradores\",\"dCallflex_agente_consolidado\",\"fCallflex_chamadas\",\"dCallflex_pausas\",\"fCallflex_chamadas_agente_detalhado\",\"fCallflex_pausas_detalhado\",\"fChat_relatorio_atendimento\",\"fChat_relatorio_resumo_usuarios\",\"fChat_relatorio_nps\",\"fAdapter_reincidencias\",\"fAdapter_atendimentos\",\"dHoras\",\"Medidas Reincidencia\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "f7a93b19-613a-4f24-bee8-ebaa12190b4f",
        "fromColumn": "Entrada",
        "fromTable": "fChat_relatorio_resumo_usuarios",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7ad32777-930b-4009-b99b-c303ee716e4f"
      },
      {
        "name": "9fd0c8a9-8edb-4122-80a6-5d99731166f6",
        "fromColumn": "Data",
        "fromTable": "fChat_relatorio_nps",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4968a8d5-4fba-4e64-8c8e-654f214cf655"
      },
      {
        "name": "d9e3836d-934c-4052-a2a0-bd12855789b7",
        "fromColumn": "DATA",
        "fromTable": "fCallflex_chamadas",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9bb371a8-6fc6-44ab-8fe7-fa1d41f0136f"
      },
      {
        "name": "5fa2a440-8a87-4883-bb63-402910d393d0",
        "fromColumn": "Data Abertura",
        "fromTable": "fAdapter_reincidencias",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f91ec5c1-d982-4e68-aa2b-141ceaf68c32"
      },
      {
        "name": "c6b90986-4b82-d3c4-bb74-2b6f6ce30c14",
        "fromColumn": "COLABORADOR",
        "fromTable": "fAdapter_atendimentos",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "d72e0bd4-4f32-41d1-b950-40a61ac3f156",
        "fromColumn": "DATA_DE_LOGIN",
        "fromTable": "fCallflex_pausas_detalhado",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d556f314-8bb0-42d9-9a44-f85e0726584a"
      },
      {
        "name": "f97139b0-e99a-4eb7-a9a5-c54ad5ee7bb6",
        "fromColumn": "Data de entrada",
        "fromTable": "fChat_relatorio_atendimento",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_402833ec-6b08-4a3c-9ab5-3bee6ab4a591"
      },
      {
        "name": "812b6e11-74cd-ae9a-6594-81e29db56e4b",
        "fromColumn": "COLABORADOR",
        "fromTable": "fChat_relatorio_resumo_usuarios",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "35a4ce39-b29f-0f1d-bb14-6f5f29d2ac09",
        "fromColumn": "COLABORADOR",
        "fromTable": "fChat_relatorio_nps",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "0be34280-2a2b-1993-d3a5-d0dbfb828d7b",
        "fromColumn": "COLABORADOR",
        "fromTable": "fCallflex_chamadas",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "80421936-8a3d-26d5-8d16-44701d6abc46",
        "fromColumn": "COLABORADOR",
        "fromTable": "fAdapter_reincidencias",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "133675e9-1516-0daa-a0cb-33abc18471db",
        "fromColumn": "COLABORADOR",
        "fromTable": "fCallflex_pausas_detalhado",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "7131ec17-f383-6c26-c7b8-3b43644ccd81",
        "fromColumn": "COLABORADOR",
        "fromTable": "fChat_relatorio_atendimento",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "929ba61c-8aba-9c1d-6fd5-a31d5568477c",
        "fromColumn": "COLABORADOR",
        "fromTable": "fCallflex_chamadas_agente_detalhado",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "87701998-aca2-5f16-1974-2a47c11537e5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "COLABORADOR",
        "fromTable": "dCallflex_agente_consolidado",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "5542920b-c8c2-e7b5-853e-d4257ba08a37",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "COLABORADOR",
        "fromTable": "dCallflex_pausas",
        "toColumn": "Colaborador",
        "toTable": "dColaboradores"
      },
      {
        "name": "4c0811fe-7e9e-4273-8c5b-6b73189ee35c",
        "fromColumn": "Hora",
        "fromTable": "fCallflex_chamadas",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a384ac4e-028b-4e81-9215-5602139dc11c"
      },
      {
        "name": "3fabf8dd-b414-4399-87ee-2e9a2b2f95f6",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e16dbdbd-ac5e-44a7-9335-501005149e3c"
      },
      {
        "name": "d3a97895-c9ee-947e-f38b-9daccc72c55f",
        "fromColumn": "Data Abertura (ddmmaaaa)",
        "fromTable": "fAdapter_atendimentos",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "fabbdef7-d2a4-89b2-62a8-3d94ee35d9d1",
        "fromColumn": "Data (ddmmaaaa)",
        "fromTable": "fChat_relatorio_resumo_usuarios",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "2ef566ad-7fa2-38bc-8fd2-fdf7fd315c3f",
        "fromColumn": "Data (ddmmaaaa)",
        "fromTable": "fChat_relatorio_nps",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "ad9ef431-2063-31b7-bf28-05c78ad34311",
        "fromColumn": "Data (ddmmaaaa)",
        "fromTable": "fCallflex_chamadas",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "84da5310-03b4-6fed-6e3a-fca4f586d51c",
        "fromColumn": "Data Abertura (ddmmaaaa)",
        "fromTable": "fAdapter_reincidencias",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "e419a1cb-263a-4de7-22b3-ae8c3a3f15f1",
        "fromColumn": "Data (ddmmaaaa)",
        "fromTable": "fCallflex_pausas_detalhado",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "04069829-46de-d3e3-4aec-d3b758aeda36",
        "fromColumn": "DATA_DE_LOGIN",
        "fromTable": "fCallflex_chamadas_agente_detalhado",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "f15323cc-4c3b-367b-ffee-9af8c867a649",
        "fromColumn": "Data (ddmmaaaa)",
        "fromTable": "fChat_relatorio_atendimento",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "a15ba565-b803-ea96-af37-c9a518f70d38",
        "fromColumn": "Hora (compartimentos)",
        "fromTable": "fChat_relatorio_atendimento",
        "toColumn": "Horas",
        "toTable": "dHoras"
      },
      {
        "name": "d9976c78-1d47-956f-40df-25481ba034a9",
        "fromColumn": "Hora (compartimentos)",
        "fromTable": "fCallflex_chamadas",
        "toColumn": "Horas",
        "toTable": "dHoras"
      },
      {
        "name": "5307732d-8821-4d32-80e8-7e4dd2fdbff7",
        "fromColumn": "Data Abertura",
        "fromTable": "fAdapter_atendimentos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6bc8eb7d-071b-4eec-8af6-bdc7027e4e08"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dCallflex_agente_consolidado",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8547387f-8370-4d4c-af8e-f741fe89b366",
            "sourceColumn": "AGENTE",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee297d5c-4bf3-4f45-a556-f06b1dfc0608",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_LOGADO_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2131bd41-fd2f-4a7c-b0e9-8f0af1890f5b",
            "sourceColumn": "TEMPO_LOGADO_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_LOGADO_MEDIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3dbc5ef-7aec-4573-8e23-5614d02a84f6",
            "sourceColumn": "TEMPO_LOGADO_MEDIO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_DESLOGADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "378d4fbd-bd89-438d-9cb9-e2e4524c2798",
            "sourceColumn": "TEMPO_DESLOGADO",
            "summarizeBy": "none"
          },
          {
            "name": "ADERENCIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c54ae003-7e7c-4509-a170-d86a92e087e9",
            "sourceColumn": "ADERENCIA",
            "summarizeBy": "none"
          },
          {
            "name": "PAUSAS_OFICIAIS_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd2794b8-fb60-4834-aaa8-a57577aae902",
            "sourceColumn": "PAUSAS_OFICIAIS_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "PAUSAS_OFICIAIS_EXCEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57eaafc5-d3f4-409a-848d-91f9db311795",
            "sourceColumn": "PAUSAS_OFICIAIS_EXCEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "PAUSA_PRODUTIVA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef94a959-57a7-4b08-9a30-e3d599cab3b0",
            "sourceColumn": "PAUSA_PRODUTIVA",
            "summarizeBy": "none"
          },
          {
            "name": "OUTRAS_PAUSAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cafb4a5a-9201-4671-ac98-701a2d27c1b6",
            "sourceColumn": "OUTRAS_PAUSAS",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_TOTAL_DE_PAUSAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac46a369-75dd-4df3-a84d-6d9a822b6ab2",
            "sourceColumn": "TEMPO_TOTAL_DE_PAUSAS",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_EM_OPERACAO_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f99db917-62db-4e5c-a4fc-0891c7dd8cfe",
            "sourceColumn": "TEMPO_EM_OPERACAO_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_EM_OPERACAO_MEDIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3051a021-941f-40f4-8559-41799666e241",
            "sourceColumn": "TEMPO_EM_OPERACAO_MEDIO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_TOTAL_DISPONIVEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58c1e4ae-9aa5-4521-971f-98abb532e4e4",
            "sourceColumn": "TEMPO_TOTAL_DISPONIVEL",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_TOTAL_INDISPONIVEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8718d63-b840-4afd-9877-6bd89a02e5c8",
            "sourceColumn": "TEMPO_TOTAL_INDISPONIVEL",
            "summarizeBy": "none"
          },
          {
            "name": "TME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25829aca-f7e6-49d0-abda-5cac41510f24",
            "sourceColumn": "TME",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_EM_ATENDIMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b995989-3539-45eb-9e7d-41873649890a",
            "sourceColumn": "TEMPO_EM_ATENDIMENTO",
            "summarizeBy": "none"
          },
          {
            "name": "TMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "252ebd6f-7e53-4bd8-a659-cc00f1bd24c5",
            "sourceColumn": "TMA",
            "summarizeBy": "none"
          },
          {
            "name": "ENTRANTES_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dc91093-dd27-441b-ab3f-2b9ef32096a3",
            "sourceColumn": "ENTRANTES_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "ENTRANTES_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e0fe96c-0b0b-4aaa-af8c-e131599c6d5f",
            "sourceColumn": "ENTRANTES_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "SAINTES_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2a98e84-9d58-42da-ab75-a5fd6422a464",
            "sourceColumn": "SAINTES_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "SAINTES_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6509ca6e-8b96-49d8-a017-f28a2bc01238",
            "sourceColumn": "SAINTES_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_AFTERCALL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb015ba4-ca72-44ec-b610-d3469b55c387",
            "sourceColumn": "TEMPO_AFTERCALL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0a32d144-d596-49b2-a9fb-42eb63d900ec",
        "partitions": [
          {
            "name": "dCallflex_agente_consolidado",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/dCallflex_agente_consolidado.xlsx\"), null, true),",
                "    Export_Sheet = Fonte{[Item=\"Relatorio_agentes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Cabeçalhos Promovidos\",{{\"AGENTE_NOME\", Text.Upper, type text}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Texto em Maiúscula\",\"---\",\"\",Replacer.ReplaceValue,{\"TMA\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"---\",\"\",Replacer.ReplaceValue,{\"TME\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_EM_ATENDIMENTO\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído2\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_TOTAL_INDISPONIVEL\"}),",
                "    #\"Valor Substituído4\" = Table.ReplaceValue(#\"Valor Substituído3\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_TOTAL_DISPONIVEL\"}),",
                "    #\"Valor Substituído5\" = Table.ReplaceValue(#\"Valor Substituído4\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_TOTAL_DE_PAUSAS\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Valor Substituído5\",{{\"AGENTE_NOME\", \"COLABORADOR\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fChat_relatorio_atendimento",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2afde58d-d6df-4d8b-aba5-1cff8c7a2527",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Protocolo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d110aa9-6436-4590-8db4-b180a3958c44",
            "sourceColumn": "Protocolo",
            "summarizeBy": "none"
          },
          {
            "name": "ID do visitante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a634b1cd-f3ca-4ee2-b05f-5191eed90de4",
            "sourceColumn": "ID do visitante",
            "summarizeBy": "none"
          },
          {
            "name": "Data de entrada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0d00374c-c6e1-4952-bb96-c3ab6b8d7e2f",
            "sourceColumn": "Data de entrada",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_402833ec-6b08-4a3c-9ab5-3bee6ab4a591"
                },
                "isDefault": true,
                "relationship": "f97139b0-e99a-4eb7-a9a5-c54ad5ee7bb6"
              }
            ]
          },
          {
            "name": "Data de inicio atendimento robô",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ca2698b-dc63-4362-a896-1fe9535e3f8f",
            "sourceColumn": "Data de inicio atendimento robô",
            "summarizeBy": "none"
          },
          {
            "name": "Data fim de atendimento robô",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd7cfb7f-171e-4fae-9ae9-11f72610e36a",
            "sourceColumn": "Data fim de atendimento robô",
            "summarizeBy": "none"
          },
          {
            "name": "Data de início de atendimento humano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90bdc9a7-0d57-4350-becc-6457250664a2",
            "sourceColumn": "Data de início de atendimento humano",
            "summarizeBy": "none"
          },
          {
            "name": "Data fim de atendimento humano - Data Final",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dda2f02d-2ea8-4d17-8269-dd9d3f5261d0",
            "sourceColumn": "Data fim de atendimento humano - Data Final",
            "summarizeBy": "none"
          },
          {
            "name": "TTE (humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6648bbc3-e4ca-4ada-9f03-0bcf4112b7d3",
            "sourceColumn": "TTE (humano)",
            "summarizeBy": "none"
          },
          {
            "name": "TTA (humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca4c5845-9765-41d1-ad15-c2a5dce0e4f6",
            "sourceColumn": "TTA (humano)",
            "summarizeBy": "none"
          },
          {
            "name": "TTA (robô)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28852eff-31dc-4f46-958f-54bef4d1c11d",
            "sourceColumn": "TTA (robô)",
            "summarizeBy": "none"
          },
          {
            "name": "TTA em agendamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dafb2b43-c72a-431d-bbbd-2afa803bff2c",
            "sourceColumn": "TTA em agendamento",
            "summarizeBy": "none"
          },
          {
            "name": "TMR de entrada (robô)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9556c63a-8715-4fd0-b8fa-6f4e47736d3f",
            "sourceColumn": "TMR de entrada (robô)",
            "summarizeBy": "none"
          },
          {
            "name": "TMR de saída (robô)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da355812-edfb-457d-a76d-05351e510e49",
            "sourceColumn": "TMR de saída (robô)",
            "summarizeBy": "none"
          },
          {
            "name": "TMR de entrada (humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c226d0fd-3194-4d12-b3fd-5bce1fa1c691",
            "sourceColumn": "TMR de entrada (humano)",
            "summarizeBy": "none"
          },
          {
            "name": "TMR de saída (humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcf42cb3-288b-48ed-be61-165545e2b6cd",
            "sourceColumn": "TMR de saída (humano)",
            "summarizeBy": "none"
          },
          {
            "name": "Total de alertas de inatividade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faf5ab0b-eaec-4e74-a5ca-45b4c94106ea",
            "sourceColumn": "Total de alertas de inatividade",
            "summarizeBy": "none"
          },
          {
            "name": "O alerta teve resultado?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cfa81c6-ac64-493b-9a83-d10514cae0a0",
            "sourceColumn": "O alerta teve resultado?",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens recebidas (Atendimento)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66e21d30-4ee5-48e4-9fc0-8b4d018508ce",
            "sourceColumn": "Mensagens recebidas (Atendimento)",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens enviadas (Atendimento)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16d08b99-4124-4171-87e2-32a28831028f",
            "sourceColumn": "Mensagens enviadas (Atendimento)",
            "summarizeBy": "none"
          },
          {
            "name": "Total de mensagens (Atendimento)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68cf9036-6f18-4aa1-92a0-10b815b3bb78",
            "sourceColumn": "Total de mensagens (Atendimento)",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57828659-5062-432f-9d01-1d236bfe47c6",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Canal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c3d191c-ae3b-4f67-a18c-a51848db7586",
            "sourceColumn": "Canal",
            "summarizeBy": "none"
          },
          {
            "name": "Info",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb749030-aed0-4fed-b197-a91c640e1e61",
            "sourceColumn": "Info",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22a3534c-aef2-476a-b8bd-424623f9f567",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário que encerrou",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93b1479a-3d78-4339-a288-95c4c1ee679d",
            "sourceColumn": "Usuário que encerrou",
            "summarizeBy": "none"
          },
          {
            "name": "Id do contato",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24ad1ba4-85af-43d0-b59c-283ff91e987e",
            "sourceColumn": "Id do contato",
            "summarizeBy": "none"
          },
          {
            "name": "Documento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ac88c7f-1122-4838-b391-26f9add5f6e9",
            "sourceColumn": "Documento",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eba06e7-a1f4-4073-bf34-11692af9b0b0",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Contato",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4123173-7ee4-480b-be02-1b7c1c106d85",
            "sourceColumn": "Contato",
            "summarizeBy": "none"
          },
          {
            "name": "Informações adicionais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37755ac7-fded-47d5-aa2b-dcb5053d24eb",
            "sourceColumn": "Informações adicionais",
            "summarizeBy": "none"
          },
          {
            "name": "Origem do atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d55fc77a-d563-4f7b-a506-55f66eda720b",
            "sourceColumn": "Origem do atendimento",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f01d41f-a8cf-494d-9a78-e43fcbfbfa2b",
            "sourceColumn": "Classificação",
            "summarizeBy": "none"
          },
          {
            "name": "Data agendada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "637b9d03-e838-40ae-a4d5-99c63121fdbe",
            "sourceColumn": "Data agendada",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo de Ocorrência",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ca6427a-65ea-419e-b16e-d330f8c8d0db",
            "sourceColumn": "Grupo de Ocorrência",
            "summarizeBy": "none"
          },
          {
            "name": "Ocorrência",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "716235e1-8143-4ca3-be8d-a108351326c4",
            "sourceColumn": "Ocorrência",
            "summarizeBy": "none"
          },
          {
            "name": "Manifestação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41a82cb3-c491-4a76-a6e8-e630a2518459",
            "sourceColumn": "Manifestação",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3156169b-29eb-4adb-a919-816bb5080127",
            "sourceColumn": "Valor",
            "summarizeBy": "none"
          },
          {
            "name": "Robô",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58f5a12c-071d-4d04-89ae-c15b75991d15",
            "sourceColumn": "Robô",
            "summarizeBy": "none"
          },
          {
            "name": "Robô origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b78cab8-126c-4650-b164-de6c2931ad2e",
            "sourceColumn": "Robô origem",
            "summarizeBy": "none"
          },
          {
            "name": "Fase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94edd9d4-42d3-4435-99e3-4ac0fa5d3c5e",
            "sourceColumn": "Fase",
            "summarizeBy": "none"
          },
          {
            "name": "CRM id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcdfb660-5e9a-4a47-b7dd-60fd5f7f93a0",
            "sourceColumn": "CRM id",
            "summarizeBy": "none"
          },
          {
            "name": "Adicional 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fec80188-80be-4fe3-9b34-6297cd0814b6",
            "sourceColumn": "Adicional 1",
            "summarizeBy": "none"
          },
          {
            "name": "Adicional 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f3ea7a2-0e44-46db-a99e-da3b55b6215e",
            "sourceColumn": "Adicional 2",
            "summarizeBy": "none"
          },
          {
            "name": "Adicional 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f47b3e-0fa1-4fee-869f-adf94c778008",
            "sourceColumn": "Adicional 3",
            "summarizeBy": "none"
          },
          {
            "name": "Adicional 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0989e44-4b22-4813-a504-19b1b0d9027a",
            "sourceColumn": "Adicional 4",
            "summarizeBy": "none"
          },
          {
            "name": "Adicional 5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ae2eaa6-9ff2-41e6-a5d8-168517e947e2",
            "sourceColumn": "Adicional 5",
            "summarizeBy": "none"
          },
          {
            "name": "Quantidade de retornos ao robô",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cde160f5-0305-4cbb-ab0b-df220b58ad26",
            "sourceColumn": "Quantidade de retornos ao robô",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo limite - SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b1e395e-5d7f-45c3-8bb0-fd84a9c0591f",
            "sourceColumn": "Tempo limite - SLA",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo executado - SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8304ac80-0ad6-4b74-bd99-608ebe02749b",
            "sourceColumn": "Tempo executado - SLA",
            "summarizeBy": "none"
          },
          {
            "name": "SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a5df60a-7870-4353-b7b7-a6ff06e213d0",
            "sourceColumn": "SLA",
            "summarizeBy": "none"
          },
          {
            "name": "Fila de atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4476394c-934f-49b7-85d5-82e5696c33cd",
            "sourceColumn": "Fila de atendimento",
            "summarizeBy": "none"
          },
          {
            "name": "Formulário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2fa6586-660a-483e-a829-48547f5873c8",
            "sourceColumn": "Formulário",
            "summarizeBy": "none"
          },
          {
            "name": "Dialogo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc386f44-b680-49a9-96f4-488e91b03c21",
            "sourceColumn": "Dialogo",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens recebidas (Robô)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fd3403a-3b8e-4832-aa81-25b6ef7da506",
            "sourceColumn": "Mensagens recebidas (Robô)",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens enviadas (Robô)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0cd653d-653d-424a-aede-5889198d84b7",
            "sourceColumn": "Mensagens enviadas (Robô)",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens recebidas (Humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba82c1f1-804d-4bf5-ae88-6ad1054c404c",
            "sourceColumn": "Mensagens recebidas (Humano)",
            "summarizeBy": "none"
          },
          {
            "name": "Mensagens enviadas (Humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4d74fcb-66a2-4b02-b981-5b8f63b59f8e",
            "sourceColumn": "Mensagens enviadas (Humano)",
            "summarizeBy": "none"
          },
          {
            "name": "Primeira mensagem (Humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "447b2c35-829d-461b-9f9b-dea9a97488dd",
            "sourceColumn": "Primeira mensagem (Humano)",
            "summarizeBy": "none"
          },
          {
            "name": "Última mensagem (Humano)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c016b60-ac09-46dc-bfb8-402646f81359",
            "sourceColumn": "Última mensagem (Humano)",
            "summarizeBy": "none"
          },
          {
            "name": "Último Usuário Humano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16b8284d-ea3d-49ba-a8c7-3e147a968c3b",
            "sourceColumn": "Último Usuário Humano",
            "summarizeBy": "none"
          },
          {
            "name": "Última mensagem (Cliente)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74c5c941-297b-46f0-8be3-aede8bb96d20",
            "sourceColumn": "Última mensagem (Cliente)",
            "summarizeBy": "none"
          },
          {
            "name": "Data (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "84cc60bd-994d-4708-9bad-77c7635a5805",
            "sourceColumn": "Data (ddmmaaaa)",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"fChat_relatorio_atendimento\",\"TableItemName\":\"Hora (compartimentos)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "945cb8c2-4bfe-49ac-8e52-fa29bae607fa",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          },
          {
            "name": "Hora (compartimentos)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"fChat_relatorio_atendimento\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"Hora\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"Hora\"}},\"Size\":1.0,\"TimeUnit\":7}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('fChat_relatorio_atendimento'[Hora]),",
              "\tBLANK(),",
              "\tINT('fChat_relatorio_atendimento'[Hora] * 24) / 24",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 9,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "fChat_relatorio_atendimento"
                          }
                        },
                        "Property": "Hora"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "Long Time",
            "lineageTag": "47a473cb-bd23-416b-89d8-12017f2a68c1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "fbaad861-a9f8-495d-a986-8aa804e1146c",
        "partitions": [
          {
            "name": "fChat_relatorio_atendimento",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fChat_relatorio_atendimento.csv\"),[Delimiter=\";\", Columns=62, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"Artur Do nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza de Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"João Vitor da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan  Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques de Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"Usuário\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"DANIELLE DA SILVA FIALHO\",{{\"Data de entrada\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data (ddmmaaaa)\", each DateTime.Date([Data de entrada]), type date),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Data Inserida\",{{\"Usuário\", \"COLABORADOR\"}}),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Hora\", each DateTime.Time([Data de entrada]), type time)",
                "in",
                "    #\"Hora Inserida\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_853ae852-e2bd-456d-8f3e-9f85d0784790",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "82ce97e4-d069-4e62-84b2-f785b096482a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f8a437c6-eece-4c8c-912d-0af41e861a05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8e4faf99-c866-4c5f-a93e-2a3b68cfb238",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ffced05e-504f-447d-9227-52e10e6b47be",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "98eb8aca-56c2-414c-9025-b6a2380c99bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3ae0f914-5d79-45ca-b6ec-5e2d22ab8daa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "86755452-cd93-4fb1-8f75-1eff41d10b14",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "7a765763-f589-4a16-8e6c-6f1985834093",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c8e2c03b-79cc-438b-a6d7-73ea0a6fe55f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "4753b96f-ef19-47e4-9655-d61200c4f96c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "cbf1afcd-962f-4450-a7c2-6e0cefd59947",
                "ordinal": 3
              }
            ],
            "lineageTag": "9b75c931-335d-437a-82e4-a379519f94d3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1cfbac03-0ae6-4f8d-8da5-88632c2b6172",
        "partitions": [
          {
            "name": "DateTableTemplate_853ae852-e2bd-456d-8f3e-9f85d0784790",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fChat_relatorio_resumo_usuarios",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc7e112c-4115-46c6-8b1c-51a6620e2dc6",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e551b0d-6cd1-464d-8bed-8696b3296429",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd704816-3ae0-4d6a-87e9-36742c8c00c5",
            "sourceColumn": "Usuário",
            "summarizeBy": "none"
          },
          {
            "name": "Entrada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5068ce7a-6224-43a0-8ba7-226cb2854ef9",
            "sourceColumn": "Entrada",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7ad32777-930b-4009-b99b-c303ee716e4f"
                },
                "isDefault": true,
                "relationship": "f7a93b19-613a-4f24-bee8-ebaa12190b4f"
              }
            ]
          },
          {
            "name": "Saída",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5a10071-7d3c-4c55-a175-92ac4d19c6b8",
            "sourceColumn": "Saída",
            "summarizeBy": "none"
          },
          {
            "name": "Perfil atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "663f34f3-18c6-4ae6-8f18-6581cf684d7b",
            "sourceColumn": "Perfil atual",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo Jornada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "487fb561-f34c-43fe-8896-db1cbd944c31",
            "sourceColumn": "Tempo Jornada",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo Pausa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41850864-2d6d-4fd6-b894-5431271466c0",
            "sourceColumn": "Tempo Pausa",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo Disponível",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2ab9db1-5c41-47fc-96cb-ea6394239a09",
            "sourceColumn": "Tempo Disponível",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo Indisponível",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23e864ad-4913-44c1-a353-2f9991dcfd1e",
            "sourceColumn": "Tempo Indisponível",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo Deslogado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bab8e16-1901-45a4-b9a7-d34d6941c3c8",
            "sourceColumn": "Tempo Deslogado",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em Pausa Outros",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd3ad76e-76c0-4ce9-ac61-a6fff1954093",
            "sourceColumn": "Tempo em Pausa Outros",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em Pausa 10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27eda4d-4120-4fc1-a629-4b715f06ac6b",
            "sourceColumn": "Tempo em Pausa 10",
            "summarizeBy": "none"
          },
          {
            "name": "Tag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1129d2a-e480-49fa-8aa6-5f5bc694702d",
            "sourceColumn": "Tag",
            "summarizeBy": "none"
          },
          {
            "name": "Data (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "41a7eb7d-d3e3-48a7-88ba-1f577f5ac349",
            "sourceColumn": "Data (ddmmaaaa)",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 2:Pausa cafe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8606b8cf-156f-456c-a1c2-7489a8222d0c",
            "sourceColumn": "Tempo em pausa - 2:Pausa cafe",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 10:Pausa Bkoffice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9284245d-bd9e-4ef6-b829-1e86d276ce58",
            "sourceColumn": "Tempo em pausa - 10:Pausa Bkoffice",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 3:Pausa pessoal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17ca40f7-c7b0-414c-9f22-adf89272299d",
            "sourceColumn": "Tempo em pausa - 3:Pausa pessoal",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 12:Pausa de 15 minutos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34e35cc0-5f28-46bc-9062-6186f52f89fe",
            "sourceColumn": "Tempo em pausa - 12:Pausa de 15 minutos",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 4:Pausa Feedback",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5860b52b-0c81-4333-ae9d-ece563a45f32",
            "sourceColumn": "Tempo em pausa - 4:Pausa Feedback",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 13:Pausa atendimento tecnico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "545760e8-9f7b-40c9-81c1-eda99124d0da",
            "sourceColumn": "Tempo em pausa - 13:Pausa atendimento tecnico",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 7:Pausa manutencao TI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d87a3c2-0f82-40d1-ab96-30ae1df50049",
            "sourceColumn": "Tempo em pausa - 7:Pausa manutencao TI",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em Pausa 8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4429096c-e26a-4b19-b637-396eec5d7a1c",
            "sourceColumn": "Tempo em Pausa 8",
            "summarizeBy": "none"
          },
          {
            "name": "Tempo em pausa - 8:Pausa Atendimento presencial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3505ccf-ed7c-4979-b8e6-c266c435d9d8",
            "sourceColumn": "Tempo em pausa - 8:Pausa Atendimento presencial",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0e9f3d83-7c86-4a28-855b-ab6d692fcc3c",
        "partitions": [
          {
            "name": "fChat_relatorio_resumo_usuarios",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fChat_relatorio_resumo_usuarios.csv\"),[Delimiter=\";\", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"Artur Do nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza de Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"João Vitor da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan  Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques de Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"Nome\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"DANIELLE DA SILVA FIALHO\",{{\"Entrada\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data (ddmmaaaa)\", each DateTime.Date([Entrada]), type date),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Data Inserida\",{{\"Nome\", \"COLABORADOR\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "faf08992-edef-487f-aee6-c4cb96b248be",
        "measures": [
          {
            "name": "Total_Atendimentos",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fChat_relatorio_atendimento) + ",
              "    COUNTROWS(fCallflex_chamadas)",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a2551d6c-7527-4fb7-a142-65fc174ccd05"
          },
          {
            "name": "Contagem_Protocolos",
            "expression": [
              "",
              "IF(ISBLANK(CALCULATE(COUNTROWS(fAdapter_atendimentos))), 0, CALCULATE(COUNTROWS(fAdapter_atendimentos)))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6cb2371b-ae01-42cf-9ca0-dec664704e33"
          },
          {
            "name": "Contagem_Protocolos_Visita",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS('fAdapter_atendimentos'),",
              "        'fAdapter_atendimentos'[Gerou Visita] = \"Sim\"",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "088eb066-37d2-48a7-a7c5-e05c7750f7f7"
          },
          {
            "name": "Média NPS Não Zero",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MediaCalculada = ",
              "    CALCULATE(",
              "        AVERAGE(fChat_relatorio_nps[NPS Inteiro]),",
              "        fChat_relatorio_nps[NPS Inteiro] <> 0",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MediaCalculada),",
              "        10,",
              "        MediaCalculada",
              "    )",
              ""
            ],
            "lineageTag": "682dad44-f250-4943-9cc3-2300aebd5b8b"
          },
          {
            "name": "Tempo_Pausas_Total",
            "expression": [
              "",
              "VAR TotalSegundosCallflex = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]),  -- Substitua 'Tabela'[Pessoa] pelo nome da tabela ou campo de filtro que está usando",
              "        VAR Callflex_Pausas = [Callflex_Pausas_Total]  -- Medida Callflex_Pausas_Total (string)",
              "        VAR Callflex_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Callflex_Pausas)) && LEN(Callflex_Pausas) = 8, ",
              "                VALUE(LEFT(Callflex_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Callflex_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Callflex_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Callflex_Valid",
              "    )",
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]),  -- Substitua 'Tabela'[Pessoa] pelo nome da tabela ou campo de filtro que está usando",
              "        VAR Chat_Pausas = [Chat_Pausas_Total]  -- Medida Chat_Pausas_Total (string)",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausas)) && LEN(Chat_Pausas) = 8, ",
              "                VALUE(LEFT(Chat_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Chat_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Chat_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "-- Soma os segundos das duas medidas",
              "VAR TotalSegundos = TotalSegundosCallflex + TotalSegundosChat",
              "",
              "-- Converte os segundos totais de volta para 'hh:mm:ss'",
              "VAR Horas = INT(TotalSegundos / 3600)  -- Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  -- Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  -- Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "a18d6e7a-6432-4411-bfde-a656c4f23557"
          },
          {
            "name": "Chat_Tempo_Disponivel",
            "expression": [
              "",
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        VAR Chat_Tempo = fChat_relatorio_resumo_usuarios[Tempo Disponível]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "4fa6dff5-9484-4bf9-b877-a29f21d1c58f"
          },
          {
            "name": "TMR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Total_TMR_Seconds =",
              "    SUMX(",
              "        fChat_relatorio_atendimento,",
              "        VAR TMR_Exit_Humano = fChat_relatorio_atendimento[TMR de saída (humano)]",
              "        -- Verifica se o valor TMR_Exit_Humano está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR TMR_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(TMR_Exit_Humano)) && LEN(TMR_Exit_Humano) = 8, ",
              "                VALUE(LEFT(TMR_Exit_Humano, 2)) * 3600 + VALUE(MID(TMR_Exit_Humano, 4, 2)) * 60 + VALUE(RIGHT(TMR_Exit_Humano, 2)),",
              "                0",
              "            )",
              "        RETURN TMR_Valid",
              "    )",
              "",
              "VAR Count_TMR_Relatorio = COUNT(fChat_relatorio_atendimento[TMR de saída (humano)])",
              "",
              "VAR Media_TMR_Seconds = ",
              "    IF(Count_TMR_Relatorio > 0, Total_TMR_Seconds / Count_TMR_Relatorio, 0)",
              "",
              "-- Conversão do TMR para o formato hh:mm:ss",
              "VAR Hours = INT(Media_TMR_Seconds / 3600)",
              "VAR Minutes = INT(MOD(Media_TMR_Seconds, 3600) / 60)",
              "VAR Seconds = INT(MOD(Media_TMR_Seconds, 60))",
              "",
              "-- Retorno no formato de tempo hh:mm:ss",
              "RETURN ",
              "    FORMAT(Hours, \"00\") & \":\" & FORMAT(Minutes, \"00\") & \":\" & FORMAT(Seconds, \"00\")",
              ""
            ],
            "lineageTag": "4eedf470-9046-4b46-a07a-6a066d93ff03"
          },
          {
            "name": "TMA_Ponderado",
            "expression": [
              "",
              "VAR Total_TMA_Relatorio_Seconds =",
              "    SUMX(",
              "        fChat_relatorio_atendimento,",
              "        VAR TTA_Humano = fChat_relatorio_atendimento[TTA (humano)]",
              "        -- Verifica se o valor TTA_Humano está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR TTA_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(TTA_Humano)) && LEN(TTA_Humano) = 8, ",
              "                VALUE(LEFT(TTA_Humano, 2)) * 3600 + VALUE(MID(TTA_Humano, 4, 2)) * 60 + VALUE(RIGHT(TTA_Humano, 2)),",
              "                0",
              "            )",
              "        RETURN TTA_Valid",
              "    )",
              "",
              "VAR Count_Protocolo_Relatorio = COUNT(fChat_relatorio_atendimento[Protocolo])",
              "",
              "VAR Media_TMA_Seconds_Relatorio = ",
              "    IF(Count_Protocolo_Relatorio > 0, Total_TMA_Relatorio_Seconds / Count_Protocolo_Relatorio, 0)",
              "",
              "-- Cálculo do TMA médio em segundos e peso para a tabela CallFlex",
              "VAR Total_TMA_CallFlex_Seconds = ",
              "    SUMX(",
              "        dCallflex_agente_consolidado,",
              "        VAR TMA_CallFlex = dCallflex_agente_consolidado[TMA]",
              "        -- Verifica se o valor TMA_CallFlex está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR TMA_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(TMA_CallFlex)) && LEN(TMA_CallFlex) = 8, ",
              "                VALUE(LEFT(TMA_CallFlex, 2)) * 3600 + VALUE(MID(TMA_CallFlex, 4, 2)) * 60 + VALUE(RIGHT(TMA_CallFlex, 2)),",
              "                0",
              "            )",
              "        RETURN TMA_Valid",
              "    )",
              "",
              "VAR Total_Peso_CallFlex = ",
              "    SUMX(",
              "        dCallflex_agente_consolidado,",
              "        VALUE(dCallflex_agente_consolidado[SAINTES_QTDE]) + VALUE(dCallflex_agente_consolidado[ENTRANTES_QTDE])",
              "    )",
              "",
              "-- Peso total combinado dos dois conjuntos de dados",
              "VAR Peso_Total = Count_Protocolo_Relatorio + Total_Peso_CallFlex",
              "",
              "-- Cálculo da média ponderada em segundos",
              "VAR TMA_Ponderado_Seconds = ",
              "    IF(Peso_Total > 0,",
              "        ((Media_TMA_Seconds_Relatorio * Count_Protocolo_Relatorio) + ",
              "        (Total_TMA_CallFlex_Seconds * Total_Peso_CallFlex)) / Peso_Total,",
              "        0",
              "    )",
              "",
              "-- Conversão do TMA ponderado para o formato hh:mm:ss",
              "VAR Hours = INT(TMA_Ponderado_Seconds / 3600)",
              "VAR Minutes = INT(MOD(TMA_Ponderado_Seconds, 3600) / 60)",
              "VAR Seconds = INT(MOD(TMA_Ponderado_Seconds, 60))",
              "",
              "-- Retorno no formato de tempo hh:mm:ss",
              "RETURN ",
              "    FORMAT(Hours, \"00\") & \":\" & FORMAT(Minutes, \"00\") & \":\" & FORMAT(Seconds, \"00\")",
              ""
            ],
            "lineageTag": "1234674f-c984-4138-8b65-5274b02ee0d9"
          },
          {
            "name": "TME_Chat",
            "expression": [
              "",
              "VAR Total_TME_Relatorio_Seconds =",
              "    SUMX(",
              "        fChat_relatorio_atendimento,",
              "        VAR TTE_Humano = fChat_relatorio_atendimento[TTE (humano)]",
              "        -- Verifica se o valor TTE_Humano está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR TTE_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(TTE_Humano)) && LEN(TTE_Humano) = 8, ",
              "                VALUE(LEFT(TTE_Humano, 2)) * 3600 + VALUE(MID(TTE_Humano, 4, 2)) * 60 + VALUE(RIGHT(TTE_Humano, 2)),",
              "                0",
              "            )",
              "        RETURN TTE_Valid",
              "    )",
              "",
              "VAR Count_TTE_Relatorio = COUNT(fChat_relatorio_atendimento[TTE (humano)])",
              "",
              "VAR Media_TME_Seconds_Relatorio = ",
              "    IF(Count_TTE_Relatorio > 0, Total_TME_Relatorio_Seconds / Count_TTE_Relatorio, 0)",
              "",
              "-- Como não há peso de outros datasets, o TME ponderado será a média do relatório",
              "VAR TME_Ponderado_Seconds = Media_TME_Seconds_Relatorio",
              "",
              "-- Conversão do TME ponderado para o formato hh:mm:ss",
              "VAR Hours = INT(TME_Ponderado_Seconds / 3600)",
              "VAR Minutes = INT(MOD(TME_Ponderado_Seconds, 3600) / 60)",
              "VAR Seconds = INT(MOD(TME_Ponderado_Seconds, 60))",
              "",
              "-- Retorno no formato de tempo hh:mm:ss",
              "RETURN ",
              "    FORMAT(Hours, \"00\") & \":\" & FORMAT(Minutes, \"00\") & \":\" & FORMAT(Seconds, \"00\")",
              ""
            ],
            "lineageTag": "c2593382-f343-4eb3-9f9d-27cccd9e3af4"
          },
          {
            "name": "Rencidencias_Visitas_Tecnicas",
            "expression": [
              "",
              "VAR Contagem = CALCULATE(",
              "    COUNTROWS(fAdapter_atendimentos),",
              "    fAdapter_atendimentos[Reincidencia Setor Atendimento] = 1,",
              "    fAdapter_atendimentos[Gerou Visita] IN ",
              "        {\"Sim\"},",
              "    fAdapter_atendimentos[Setor Atendimento] IN ",
              "        {\"Suporte\"}",
              ")",
              "RETURN ",
              "IF(Contagem = 0, 0, Contagem)"
            ],
            "formatString": "0",
            "lineageTag": "4def38a8-6ace-40bf-9fd7-c5c21233ef71"
          },
          {
            "name": "Nome do Agente",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE('fAdapter_atendimentos'[COLABORADOR]), ",
              "    VALUES('fAdapter_atendimentos'[COLABORADOR]), ",
              "    \"Todos\"",
              ")",
              ""
            ],
            "lineageTag": "1bf2ff8b-f444-45b9-a192-6baf960d1052"
          },
          {
            "name": "Chat_Pausas_Total",
            "expression": [
              "",
              "VAR TotalSegundosPausado = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        VAR Chat_Pausa = fChat_relatorio_resumo_usuarios[Tempo Pausa]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausa)) && LEN(Chat_Pausa) = 8, ",
              "                VALUE(LEFT(Chat_Pausa, 2)) * 3600 + VALUE(MID(Chat_Pausa, 4, 2)) * 60 + VALUE(RIGHT(Chat_Pausa, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundosIndisponivel = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        VAR Chat_Indisponivel = fChat_relatorio_resumo_usuarios[Tempo Indisponível]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Indisponivel)) && LEN(Chat_Indisponivel) = 8, ",
              "                VALUE(LEFT(Chat_Indisponivel, 2)) * 3600 + VALUE(MID(Chat_Indisponivel, 4, 2)) * 60 + VALUE(RIGHT(Chat_Indisponivel, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosIndisponivel + TotalSegundosPausado  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "ff5ab37a-5cad-4d44-9645-57c9a7ad0f39"
          },
          {
            "name": "Atendimentos_Receptivos_Combinados",
            "expression": [
              "",
              "CALCULATE (",
              "    COUNTROWS (fChat_relatorio_atendimento), ",
              "    fChat_relatorio_atendimento[Origem do atendimento] = \"Receptivo\"",
              ") ",
              "+ ",
              "CALCULATE (",
              "    COUNTROWS (fCallflex_chamadas), ",
              "    fCallflex_chamadas[TIPO] IN {\"Entrante\", \"Interna\", \"Discador\"}",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5dcce8e3-679d-4adb-901a-5023bc1c59f5"
          },
          {
            "name": "Atendimentos_Ativos_Combinados",
            "expression": [
              "",
              "CALCULATE (",
              "    COUNTROWS (fChat_relatorio_atendimento), ",
              "    fChat_relatorio_atendimento[Origem do atendimento] = \"Ativo\"",
              ") ",
              "+ ",
              "CALCULATE (",
              "    COUNTROWS (fCallflex_chamadas), ",
              "    fCallflex_chamadas[TIPO] = \"Sainte\"",
              ") ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b4840d26-5f7c-4653-9e4e-43993436901c"
          },
          {
            "name": "% Documentação",
            "expression": [
              "DIVIDE( [Contagem_Protocolos], [Total_Atendimentos], 0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2756c6fe-e68b-4622-b822-da05a4866b40"
          },
          {
            "name": "% Conversão de OS",
            "expression": [
              "DIVIDE([Contagem_Protocolos_Visita], [Total_Atendimentos], 0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "eb08d657-383b-4ec7-90c9-ce0276863fd7"
          },
          {
            "name": "Total_Atendimentos_Chat",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fChat_relatorio_atendimento)",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d1bf6c3e-1a45-48c9-bf4b-f4a2498fcbb5"
          },
          {
            "name": "Total_Atendimentos_Callflex",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fCallflex_chamadas)",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "371b65e2-8558-4341-ba0b-33977bab0d3a"
          },
          {
            "name": "% Avaliação",
            "expression": [
              "",
              "VAR TotalLinhas = COUNTROWS(fChat_relatorio_nps)  -- Conta o total de linhas",
              "VAR LinhasDiferenteDeZero = COUNTROWS(",
              "    FILTER(",
              "        fChat_relatorio_nps, ",
              "        fChat_relatorio_nps[NPS Inteiro] <> 0",
              "    )",
              ")  -- Conta as linhas onde NPS Inteiro é diferente de 0",
              "VAR Resultado = ",
              "    IF(",
              "        TotalLinhas = 0, ",
              "        0,  -- Se não houver linhas, retorna 0%",
              "        DIVIDE(LinhasDiferenteDeZero, TotalLinhas, 0)  -- Calcula o percentual",
              "    )",
              "RETURN ",
              "    IF(ISBLANK(Resultado), 0, Resultado)  -- Se o resultado for em branco, retorna 0",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e8dc78b4-a68b-4c5a-9b2d-e6e377809b17"
          },
          {
            "name": "% Resolução no 1º Contato",
            "expression": [
              "",
              "([Total_Atendimentos] - ([Rencidencias_Visitas_Tecnicas] + [Rencidencias_Atendimentos])) / [Total_Atendimentos]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fd0869d4-a76e-41fa-aabc-16f659af1489"
          },
          {
            "name": "Contagem_POS_ATENDIMENTO",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "        COUNTROWS(",
              "            FILTER(",
              "                'fAdapter_atendimentos',",
              "                'fAdapter_atendimentos'[Status] = \"POS_ATENDIMENTO\"",
              "            )",
              "        )",
              "    ),",
              "    0,",
              "    COUNTROWS(",
              "        FILTER(",
              "            'fAdapter_atendimentos',",
              "            'fAdapter_atendimentos'[Status] = \"POS_ATENDIMENTO\"",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "320d3a1f-4f60-484d-98cf-b704058275b4"
          },
          {
            "name": "Pós_Atendimento",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE([Contagem_Protocolos_Visita] - [Contagem_POS_ATENDIMENTO], [Contagem_Protocolos_Visita], 1)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fd2a19a6-d182-4631-aede-cc137caa7567"
          },
          {
            "name": "Bonificação",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR TME_Em_Segundos = ",
              "    HOUR([TME_Chat]) * 3600 + ",
              "    MINUTE([TME_Chat]) * 60 + ",
              "    SECOND([TME_Chat])",
              "",
              "VAR Doc = MIN(VALUE([% Documentação]), 100)  -- Doc em %",
              "VAR Res1Cont = MIN(VALUE([% Resolução no 1º Contato]), 100)  -- Res1Cont em %",
              "VAR NPS = VALUE([Média NPS Não Zero])  -- NPS em decimal",
              "VAR PosAt = MIN(VALUE([Pós_Atendimento]), 100)  -- PosAt em %",
              "",
              "-- Valor máximo de TME em segundos (ajustar conforme necessário)",
              "VAR TME_Max_Segundos = 3600  -- Exemplo: 1 hora (3600 segundos)",
              "VAR TME_Invertido = (TME_Max_Segundos - TME_Em_Segundos) / TME_Max_Segundos * 100",
              "",
              "-- Calcular a pontuação",
              "VAR Pontuacao = ",
              "    (Doc * 15 + ",
              "    Res1Cont * 15 + ",
              "    NPS * 25 + ",
              "    PosAt * 5 + ",
              "    TME_Invertido * 25 + ",
              "    100 * 15) / 100",
              "",
              "RETURN ",
              "    MIN((Pontuacao / 100) * 150, 150)",
              ""
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1ecd5d20-b700-4b5f-9111-17b3a33776c5"
          },
          {
            "name": "% Atingimento Máximo",
            "expression": [
              "DIVIDE([Bonificação], 150, 0) * 100",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "98b24de4-bf50-4cb4-b379-cacf2c4540d3"
          },
          {
            "name": "PercentualFaltante",
            "expression": [
              "100 - [% Atingimento Máximo]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "01321a59-c251-4cae-a8aa-dcaf11889ad2"
          },
          {
            "name": "TME_Em_Segundos",
            "expression": [
              "",
              "HOUR([TME_Chat]) * 3600 + MINUTE([TME_Chat]) * 60 + SECOND([TME_Chat])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a6886046-ceb8-49e6-af7f-2b3e4fbb69f7"
          },
          {
            "name": "Em Construção",
            "expression": "\"---\"",
            "lineageTag": "d811548d-9e36-44fc-a4b9-a886e6504b67"
          },
          {
            "name": "Callflex_Tempo_Disponivel",
            "expression": [
              "",
              "VAR TotalSegundosCallflex = ",
              "    SUMX(",
              "        fCallflex_chamadas_agente_detalhado,",
              "        VAR Callflex_Tempo = fCallflex_chamadas_agente_detalhado[TEMPO_DISPONIVEL]",
              "        -- Verifica se o valor Callflex_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Callflex_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Callflex_Tempo)) && LEN(Callflex_Tempo) = 8, ",
              "                VALUE(LEFT(Callflex_Tempo, 2)) * 3600 + VALUE(MID(Callflex_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Callflex_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Callflex_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosCallflex  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "4577b00a-e88d-43d1-933f-4835f65aca1d"
          },
          {
            "name": "Callflex_Pausas_Total",
            "expression": [
              "",
              "VAR TotalSegundosPausado = ",
              "    SUMX(",
              "        fCallflex_pausas_detalhado,",
              "        VAR Chat_Pausa = fCallflex_pausas_detalhado[TEMPO_PAUSADO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausa)) && LEN(Chat_Pausa) = 8, ",
              "                VALUE(LEFT(Chat_Pausa, 2)) * 3600 + VALUE(MID(Chat_Pausa, 4, 2)) * 60 + VALUE(RIGHT(Chat_Pausa, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosPausado  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "074f7094-32fb-4abc-b16a-1da270ca184c"
          },
          {
            "name": "Chat_Soma_Tempo_Indisponível",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo Indisponível])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "f0da1d43-cda6-40ec-a77f-2d9ca9d53085"
          },
          {
            "name": "Chat_Contagem_Pausa_Indisponivel",
            "expression": [
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo Indisponível] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "347165fc-3103-4230-a851-4f2d1615485f"
          },
          {
            "name": "Chat_Soma_Tempo_Refeicao",
            "expression": [
              "\"00:00:00\"",
              "// VAR TotalTempo = ",
              "//     SUMX(",
              "//         fChat_relatorio_resumo_usuarios,",
              "//         TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - Pausa refeição])",
              "//     )",
              "// RETURN ",
              "//     IF(",
              "//         TotalTempo = 0,",
              "//         TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "//         TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "//     )",
              "    ",
              "",
              "",
              ""
            ],
            "lineageTag": "b743fe43-7930-4f5e-b656-b48c2a9aa699"
          },
          {
            "name": "Chat_Contagem_Pausa_Refeicao",
            "expression": [
              "\"0\"",
              "// VAR LinhasComTempoValido = ",
              "//     FILTER(",
              "//         fChat_relatorio_resumo_usuarios,",
              "//         fChat_relatorio_resumo_usuarios[Tempo em pausa - Pausa refeição] <> \"00:00:00\"",
              "//     )",
              "// RETURN ",
              "//     IF(",
              "//         COUNTROWS(LinhasComTempoValido) = 0, ",
              "//         0, ",
              "//         COUNTROWS(LinhasComTempoValido)",
              "//     )",
              "",
              "",
              ""
            ],
            "lineageTag": "75b82b48-4f3d-46a1-bf6e-1bf1ae593bd7"
          },
          {
            "name": "Chat_Soma_Tempo_Pessoal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 3:Pausa pessoal])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "07f8d3de-2717-4972-8c25-1943e9637bc6"
          },
          {
            "name": "Chat_Contagem_Pausa_Pessoal",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 3:Pausa pessoal] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a13b6f03-0e72-4ac5-9bfc-b99085ab65d5"
          },
          {
            "name": "Chat_Soma_Tempo_Feedback",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 4:Pausa Feedback])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "907fd0c0-3880-493c-9096-4e585b6114d2"
          },
          {
            "name": "Chat_Contagem_Pausa_Feedback",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 4:Pausa Feedback] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "728b8558-ae4a-4cff-9a0e-dc94dc2adb77"
          },
          {
            "name": "Chat_Soma_Tempo_ManutencaoTi",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 7:Pausa manutencao TI])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "bb210ade-5116-4cff-9ef0-0cc84989dbd9"
          },
          {
            "name": "Chat_Contagem_Pausa_ManutencaoTi",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 7:Pausa manutencao TI] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c0c7cec2-d722-4e21-90d7-f827fca632c7"
          },
          {
            "name": "Chat_Soma_Tempo_AtendimentoPresencial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 8:Pausa Atendimento presencial])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "ad595a60-9396-42b9-bfa4-a6865d4d41ca"
          },
          {
            "name": "Chat_Contagem_Pausa_AtendimentoPresencial",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 8:Pausa Atendimento presencial] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a602a14c-df19-45d5-add0-c05765f9df07"
          },
          {
            "name": "Chat_Soma_Tempo_Backoffice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 10:Pausa Bkoffice])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "81797462-c5f7-486f-90b2-b1daa8ef1441"
          },
          {
            "name": "Chat_Contagem_Pausa_Backoffice",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 10:Pausa Bkoffice] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "41cdad7e-6038-43c1-a65e-0b3e048c9ed5"
          },
          {
            "name": "Chat_Soma_Tempo_15Min",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em Pausa 10])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "be022962-0c34-49ac-9b51-3d8d6b2c6495"
          },
          {
            "name": "Chat_Contagem_Pausa_15Min",
            "expression": [
              "",
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em Pausa 10] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "01cd69e6-471a-4c3e-af08-3b9d265a693a"
          },
          {
            "name": "Chat_Contagem_Pausa_AtendimentoTecnico",
            "expression": [
              "",
              "VAR LinhasComTempoValido = ",
              "    FILTER(",
              "        fChat_relatorio_resumo_usuarios,",
              "        fChat_relatorio_resumo_usuarios[Tempo em pausa - 13:Pausa atendimento tecnico] <> \"00:00:00\"",
              "    )",
              "RETURN ",
              "    IF(",
              "        COUNTROWS(LinhasComTempoValido) = 0, ",
              "        0, ",
              "        COUNTROWS(LinhasComTempoValido)",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bd9274a0-0cfe-43d2-91ff-82e4a0cebfcd"
          },
          {
            "name": "Tempo_Disponivel_Total",
            "expression": [
              "",
              "VAR TotalSegundosCallflex = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]),  -- Substitua 'Tabela'[Pessoa] pelo nome da tabela ou campo de filtro que está usando",
              "        VAR Callflex_Pausas = [Callflex_Tempo_Disponivel]  -- Medida Callflex_Pausas_Total (string)",
              "        VAR Callflex_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Callflex_Pausas)) && LEN(Callflex_Pausas) = 8, ",
              "                VALUE(LEFT(Callflex_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Callflex_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Callflex_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Callflex_Valid",
              "    )",
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]),  -- Substitua 'Tabela'[Pessoa] pelo nome da tabela ou campo de filtro que está usando",
              "        VAR Chat_Pausas = [Chat_Tempo_Disponivel]  -- Medida Chat_Pausas_Total (string)",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausas)) && LEN(Chat_Pausas) = 8, ",
              "                VALUE(LEFT(Chat_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Chat_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Chat_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "-- Soma os segundos das duas medidas",
              "VAR TotalSegundos = TotalSegundosCallflex + TotalSegundosChat",
              "",
              "-- Converte os segundos totais de volta para 'hh:mm:ss'",
              "VAR Horas = INT(TotalSegundos / 3600)  -- Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  -- Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  -- Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "24a8c81c-91e5-46d5-be92-950e0fcafed4"
          },
          {
            "name": "Chat_Soma_Tempo_AtendimentoTecnico",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TotalTempo = ",
              "    SUMX(",
              "        fChat_relatorio_resumo_usuarios,",
              "        TIMEVALUE(fChat_relatorio_resumo_usuarios[Tempo em pausa - 13:Pausa atendimento tecnico])",
              "    )",
              "RETURN ",
              "    IF(",
              "        TotalTempo = 0,",
              "        TIME(0, 0, 0),  -- Retorna 00:00:00 se o total for zero",
              "        TotalTempo       -- Caso contrário, retorna o total do tempo (em segundos ou minutos, dependendo do formato)",
              "    )",
              "    ",
              ""
            ],
            "formatString": "hh:nn:ss",
            "lineageTag": "05de8314-603b-499f-9d29-c41c8db1fc77"
          },
          {
            "name": "Tempo_Pausas_Total_Segundos2",
            "expression": [
              "",
              "VAR TotalSegundosCallflex = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]), ",
              "        VAR Callflex_Pausas = [Callflex_Pausas_Total]  ",
              "        VAR Callflex_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Callflex_Pausas)) && LEN(Callflex_Pausas) = 8, ",
              "                VALUE(LEFT(Callflex_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Callflex_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Callflex_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Callflex_Valid",
              "    )",
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]), ",
              "        VAR Chat_Pausas = [Chat_Pausas_Total]  ",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausas)) && LEN(Chat_Pausas) = 8, ",
              "                VALUE(LEFT(Chat_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Chat_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Chat_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "-- Soma os segundos das duas medidas",
              "VAR TotalSegundos = TotalSegundosCallflex + TotalSegundosChat",
              "",
              "-- Retorna o valor total em segundos (não em formato de texto)",
              "RETURN TotalSegundos",
              ""
            ],
            "formatString": "0",
            "lineageTag": "506e4305-2883-4c8d-b7ad-c7a1b82b8241"
          },
          {
            "name": "Tempo_Disponível_Total_Segundos2",
            "expression": [
              "",
              "VAR TotalSegundosCallflex = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]), ",
              "        VAR Callflex_Pausas = [Callflex_Tempo_Disponivel]  ",
              "        VAR Callflex_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Callflex_Pausas)) && LEN(Callflex_Pausas) = 8, ",
              "                VALUE(LEFT(Callflex_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Callflex_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Callflex_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Callflex_Valid",
              "    )",
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        VALUES('dCallflex_agente_consolidado'[COLABORADOR]), ",
              "        VAR Chat_Pausas = [Callflex_Tempo_Disponivel]  ",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Pausas)) && LEN(Chat_Pausas) = 8, ",
              "                VALUE(LEFT(Chat_Pausas, 2)) * 3600 + ",
              "                VALUE(MID(Chat_Pausas, 4, 2)) * 60 + ",
              "                VALUE(RIGHT(Chat_Pausas, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "-- Soma os segundos das duas medidas",
              "VAR TotalSegundos = TotalSegundosCallflex + TotalSegundosChat",
              "",
              "-- Retorna o valor total em segundos (não em formato de texto)",
              "RETURN TotalSegundos",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5c304d1a-db0e-46dd-82ed-95ab20a2fc72"
          },
          {
            "name": "% Conversão de OS Documentado",
            "expression": [
              "DIVIDE([Contagem_Protocolos_Visita], [Contagem_Protocolos], 0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7c2593f1-3b89-461c-b907-9d929ac47f99"
          },
          {
            "name": "Callflex_Soma_Tempo_Pessoal",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[3-PAUSA PESSOAL-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "043d918b-1fa1-4765-9216-91f07390334a"
          },
          {
            "name": "Callflex_Contagem_Pausa_Pessoal",
            "expression": "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[3-PAUSA PESSOAL-QTDE]))",
            "formatString": "0",
            "lineageTag": "26350929-244d-4a40-8214-f4f2f713ddf6"
          },
          {
            "name": "Callflex_Contagem_Pausa_Cafe",
            "expression": "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[2-PAUSA CAFE-QTDE]))",
            "formatString": "0",
            "lineageTag": "2789b86a-9cfd-487a-8db0-75af73e5e009"
          },
          {
            "name": "Callflex_Soma_Tempo_Cafe",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[2-PAUSA CAFE-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "5dedd2d8-388e-4617-822d-cc272b9e7ad1"
          },
          {
            "name": "Callflex_Soma_Tempo_Indisponivel",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[1-INDISPONIVEL-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "4704bda2-bf59-49bd-955f-5fb29c351f25"
          },
          {
            "name": "Callflex_Contagem_Pausa_Indisponivel",
            "expression": "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[1-INDISPONIVEL-QTDE]))",
            "formatString": "0",
            "lineageTag": "3c4ee790-834c-48ab-8a6f-b4f7284b431f"
          },
          {
            "name": "Callflex_Soma_Tempo_Atendimento_Tecnico",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[13-PAUSA ATENDIMENTO TECNICO-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")"
            ],
            "lineageTag": "421f5261-b4a0-4b00-b3f3-0ba90a4188db"
          },
          {
            "name": "Callflex_Contagem_Pausa_Atendimento_Tecnico",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[13-PAUSA ATENDIMENTO TECNICO-QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bebd3ada-37dc-4904-80d1-0a64869a8f37"
          },
          {
            "name": "Callflex_Soma_Tempo_15Minutos",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[12-PAUSA DE 15 MINUTOS-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "e5345734-04ab-4814-9204-7e16d0f5028a"
          },
          {
            "name": "Callflex_Contagem_Pausa_15Minutos",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[12-PAUSA DE 15 MINUTOS-QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a08d1522-44a7-4d53-9975-b0ff0ed22955"
          },
          {
            "name": "Callflex_Soma_Tempo_Bkoffice",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[10-PAUSA BKOFFICE-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "79c9d0d6-fec1-40a3-8d43-a1f70260da48"
          },
          {
            "name": "Callflex_Contagem_Pausa_Bkoffice",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[10-PAUSA BKOFFICE-QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "78bb42b6-eb6f-4de0-9558-1cfb3466bc64"
          },
          {
            "name": "Callflex_Soma_Tempo_Atendimento_Presencial",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[8-PAUSA ATENDIMENTO PRESENCIAL -TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")"
            ],
            "lineageTag": "1bccd038-ae35-4f96-9ab1-f5023a040551"
          },
          {
            "name": "Callflex_Contagem_Pausa_Atendimento_Presencial",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[8-PAUSA ATENDIMENTO PRESENCIAL -QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "49d3f17a-5dd5-4fa0-a9cc-3f46cbf111bc"
          },
          {
            "name": "Callflex_Soma_Tempo_ManutencaoTI",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[7-PAUSA MANUTENCAO TI-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")",
              ""
            ],
            "lineageTag": "af0bb435-c0a7-4c5b-b1b7-ce7fa4a1690f"
          },
          {
            "name": "Callflex_Contagem_Pausa_ManutencaoTI",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[7-PAUSA MANUTENCAO TI-QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8bb909aa-fb45-4053-8478-baf1516f32b1"
          },
          {
            "name": "Callflex_Soma_Tempo_Feedback",
            "expression": [
              "",
              "VAR TotalSegundosChat = ",
              "    SUMX(",
              "        dCallflex_pausas,",
              "        VAR Chat_Tempo = dCallflex_pausas[4-PAUSA FEEDBACK-TEMPO]",
              "        -- Verifica se o valor Chat_Tempo está no formato de tempo 'hh:mm:ss' ou não, e converte para segundos",
              "        VAR Chat_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(Chat_Tempo)) && LEN(Chat_Tempo) = 8, ",
              "                VALUE(LEFT(Chat_Tempo, 2)) * 3600 + VALUE(MID(Chat_Tempo, 4, 2)) * 60 + VALUE(RIGHT(Chat_Tempo, 2)),",
              "                0",
              "            )",
              "        RETURN Chat_Valid",
              "    )",
              "",
              "VAR TotalSegundos = TotalSegundosChat  // Soma os segundos",
              "VAR Horas = INT(TotalSegundos / 3600)  // Calcula as horas",
              "VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)  // Calcula os minutos restantes",
              "VAR Segundos = INT(MOD(TotalSegundos, 60))  // Calcula os segundos restantes",
              "",
              "-- Retorna o resultado no formato de tempo 'hh:mm:ss'",
              "RETURN ",
              "    FORMAT(Horas, \"00\") & \":\" & FORMAT(Minutos, \"00\") & \":\" & FORMAT(Segundos, \"00\")"
            ],
            "lineageTag": "2edf2f75-6cda-421d-95de-a86f74ea2bf5"
          },
          {
            "name": "Callflex_Contagem_Pausa_Feedback",
            "expression": [
              "SUMX(dCallflex_pausas, VALUE(dCallflex_pausas[4-PAUSA FEEDBACK-QTDE]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "92a64f3e-c6b3-4615-a6f1-d401c28e57b2"
          },
          {
            "name": "TMA_Chat",
            "expression": [
              "",
              "VAR Total_TMA_Relatorio_Seconds =",
              "    SUMX(",
              "        fChat_relatorio_atendimento,",
              "        VAR TTA_Humano = fChat_relatorio_atendimento[TTA (humano)]",
              "        VAR TTA_Valid = ",
              "            IF(",
              "                NOT(ISBLANK(TTA_Humano)) && LEN(TTA_Humano) = 8, ",
              "                VALUE(LEFT(TTA_Humano, 2)) * 3600 + VALUE(MID(TTA_Humano, 4, 2)) * 60 + VALUE(RIGHT(TTA_Humano, 2)),",
              "                0",
              "            )",
              "        RETURN TTA_Valid",
              "    )",
              "",
              "VAR Count_Protocolo_Relatorio = COUNT(fChat_relatorio_atendimento[Protocolo])",
              "",
              "VAR Media_TMA_Seconds_Relatorio = ",
              "    IF(Count_Protocolo_Relatorio > 0, Total_TMA_Relatorio_Seconds / Count_Protocolo_Relatorio, 0)",
              "",
              "-- Conversão do TMA médio para o formato hh:mm:ss",
              "VAR Hours = INT(Media_TMA_Seconds_Relatorio / 3600)",
              "VAR Minutes = INT(MOD(Media_TMA_Seconds_Relatorio, 3600) / 60)",
              "VAR Seconds = INT(MOD(Media_TMA_Seconds_Relatorio, 60))",
              "",
              "RETURN ",
              "    FORMAT(Hours, \"00\") & \":\" & FORMAT(Minutes, \"00\") & \":\" & FORMAT(Seconds, \"00\")",
              ""
            ],
            "lineageTag": "abf7831a-6ba8-41f7-aa4b-e215084a3c73"
          },
          {
            "name": "TMA_Callflex",
            "expression": [
              "",
              "VAR Total_TMA_Seconds =",
              "    AVERAGEX(",
              "        fCallflex_chamadas,",
              "        VAR TMA_CallFlex = fCallflex_chamadas[TEMPO_DE_CONVERSACAO]",
              "        VAR TMA_Seconds = ",
              "            IF(",
              "                NOT(ISBLANK(TMA_CallFlex)) && LEN(TMA_CallFlex) = 8,",
              "                VALUE(LEFT(TMA_CallFlex, 2)) * 3600 + VALUE(MID(TMA_CallFlex, 4, 2)) * 60 + VALUE(RIGHT(TMA_CallFlex, 2)),",
              "                0",
              "            )",
              "        RETURN TMA_Seconds",
              "    )",
              "",
              "-- Conversão para hh:mm:ss",
              "VAR Hours = INT(Total_TMA_Seconds / 3600)",
              "VAR Minutes = INT(MOD(Total_TMA_Seconds, 3600) / 60)",
              "VAR Seconds = MOD(Total_TMA_Seconds, 60)",
              "",
              "RETURN ",
              "    FORMAT(Hours, \"00\") & \":\" & FORMAT(Minutes, \"00\") & \":\" & FORMAT(Seconds, \"00\")",
              ""
            ],
            "lineageTag": "b387a99d-a5a0-42df-938c-3c54192bb0df"
          },
          {
            "name": "Rencidencias_Atendimentos",
            "expression": [
              "",
              "VAR Contagem = CALCULATE(",
              "    COUNTROWS(fAdapter_atendimentos),",
              "    fAdapter_atendimentos[Reincidencia Setor Atendimento] = 1,",
              "    fAdapter_atendimentos[Gerou Visita] IN ",
              "        {\"Não\"},",
              "    fAdapter_atendimentos[Setor Atendimento] IN ",
              "        {\"Suporte\"}",
              ")",
              "RETURN ",
              "IF(Contagem = 0, 0, Contagem)"
            ],
            "formatString": "0",
            "lineageTag": "90f6a38e-d86b-4f26-b5e0-7a5311f13eb3"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fChat_relatorio_nps",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fc1083b-fe4a-41c3-b4a8-73eb673f7a31",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "acc5f5a2-51f1-4442-b325-81e664824a7f",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_4968a8d5-4fba-4e64-8c8e-654f214cf655"
                },
                "isDefault": true,
                "relationship": "9fd0c8a9-8edb-4122-80a6-5d99731166f6"
              }
            ]
          },
          {
            "name": "Canal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cef19b77-ae1f-4a3e-a481-d00b515dde04",
            "sourceColumn": "Canal",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20431df2-3364-4070-973a-bbcc4267823b",
            "sourceColumn": "Usuário",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c993041f-500f-4032-bf3c-6ef642775fd1",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "Person ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1069745-f4cc-452f-8ae2-f85b731d2f80",
            "sourceColumn": "Person ID",
            "summarizeBy": "none"
          },
          {
            "name": "Documento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33394e5c-fb82-4fe3-811c-993938f03818",
            "sourceColumn": "Documento",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a629351-cdaa-4438-853e-901afb8879d7",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Fase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdb9dba9-b921-4ccc-afcc-2539476b0a9a",
            "sourceColumn": "Fase",
            "summarizeBy": "none"
          },
          {
            "name": "Info",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d7bf385-b3f6-4d54-bf58-6d481657cb71",
            "sourceColumn": "Info",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b017ca-9a6b-4504-b133-45dcca3e25c2",
            "sourceColumn": "NPS",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9a05c01-d444-46cc-b206-a74411a54dd2",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          },
          {
            "name": "Robô",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9983d3fb-a5a6-407d-b777-bea7d4882099",
            "sourceColumn": "Robô",
            "summarizeBy": "none"
          },
          {
            "name": "NPS Inteiro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e42b329-853a-464d-90de-58f9071ddd6e",
            "sourceColumn": "NPS Inteiro",
            "summarizeBy": "none"
          },
          {
            "name": "Data (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "04e7c09d-213e-48c8-b478-8bc5752d142b",
            "sourceColumn": "Data (ddmmaaaa)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "af7617c8-eb0e-4ff1-9d4c-4aed55892c94",
        "partitions": [
          {
            "name": "fChat_relatorio_nps",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fChat_relatorio_nps.csv\"),[Delimiter=\";\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Cabeçalhos Promovidos\", \"NPS\", \"NPS - Copiar\"),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Coluna Duplicada\",{\"Id\", \"Data\", \"Canal\", \"Usuário\", \"Nome do Usuário\", \"Person ID\", \"Documento\", \"Nome\", \"Fase\", \"Info\", \"NPS\", \"NPS - Copiar\", \"Descrição\", \"Robô\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Reordenadas\",{{\"NPS - Copiar\", \"NPS Inteiro\"}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Renomeadas\",\"-\",\"0\",Replacer.ReplaceText,{\"NPS Inteiro\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"NPS Inteiro\", Int64.Type}}),",
                "",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Tipo Alterado1\",\"Artur Do nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza de Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"João Vitor da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan  Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques de Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"Nome do Usuário\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"DANIELLE DA SILVA FIALHO\",{{\"Data\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data (ddmmaaaa)\", each DateTime.Date([Data]), type date),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Data Inserida\",{{\"Nome do Usuário\", \"COLABORADOR\"}})",
                "in",
                "    #\"Colunas Renomeadas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fAdapter_reincidencias",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Protocolo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef33d508-2144-42ad-b66e-6f8a4205c3dc",
            "sourceColumn": "Protocolo",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce02b902-155b-4383-9243-f42e0de1de50",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Reincidencia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0465cea7-e6e9-4158-8f9c-186d7731ce72",
            "sourceColumn": "Reincidencia",
            "summarizeBy": "sum"
          },
          {
            "name": "Data Abertura",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0b6ea1a8-9a56-40a0-87e6-99ff1f70a0d0",
            "sourceColumn": "Data Abertura",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_f91ec5c1-d982-4e68-aa2b-141ceaf68c32"
                },
                "isDefault": true,
                "relationship": "5fa2a440-8a87-4883-bb63-402910d393d0"
              }
            ]
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e33c0d73-3d36-47fa-a7be-ee0269e02f32",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "AtendimentoGrupo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827d309c-b08c-48df-b0e2-2c7ecf9a190a",
            "sourceColumn": "AtendimentoGrupo",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cfd73cb-144b-4765-a921-10c507396257",
            "sourceColumn": "Tipo Atendimento",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4851ddd-9b9a-4adc-9fc8-bd8b74c19cc4",
            "sourceColumn": "Tipo Pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "Gerou Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b150ab30-1166-4723-baf4-eca38a3057d7",
            "sourceColumn": "Gerou Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Data Abertura (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4fde7fee-7252-4f3e-8a21-cab295a29340",
            "sourceColumn": "Data Abertura (ddmmaaaa)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a39c04ad-eebc-4223-93e8-7e6d7a2c2362",
        "partitions": [
          {
            "name": "fAdapter_reincidencias",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fAdapter_reincidencias.csv\"),[Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"ARTUR DO NASCIMENTO ARBOLEIA\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"MARIA LUIZA DE SOUZA PEREIRA\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"WELLINGTON DIONIZIO SANTOS\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"GIOVANNI QUINTINO DA SILVA\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"FERNANDO ALVES BARBOSA\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"CLEISON RODRIGUES DA SILVA\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"HIGOR VINICIUS RODRIGUES BRITO\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"JOÃO VITOR DA SILVA PIMENTEL\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"RENAN LUIZ GONDO DA SILVA\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"MATHEUS ANDRADE DE ARAUJO\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"ADREAN FELIPPE MATTOS DE MOURA\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"SABRINA PADIAL\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"VINICIUS NUNES RODRIGUES\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"ESTEBAN GABRIEL GARDIM DIAZ\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"RIAN DOS SANTOS ESTEVO\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"RENAN DUARTE MARQUES DE LIMA\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"DOUGLAS LISBOA SILVANO\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"ANA LUIZA SBAIS COSTA\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"BIANCA NUNES COSTA\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"DANIELLE DA SILVA FIALHO\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"DANIELLE DA SILVA FIALHO\",{{\"Data Abertura\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data Abertura (ddmmaaaa)\", each DateTime.Date([Data Abertura]), type date),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Data Inserida\",{{\"Usuário Abertura\", \"COLABORADOR\"}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"Reincidencia\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas Instalação",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "99c44bba-eb6b-4669-ae90-ef3cdfd66ade",
        "measures": [
          {
            "name": "Instalação_Pendentes",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"PENDENTE\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "87ee08b3-eb8e-46c2-8746-11f672cbc6af"
          },
          {
            "name": "Instalação_Solucionado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fAdapter_atendimentos),",
              "    ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "    fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "    fAdapter_atendimentos[Status] IN {\"SOLUCIONADO\"}",
              ")",
              ""
            ],
            "lineageTag": "7d823e60-33aa-45b7-ad11-3938d5e19dd8"
          },
          {
            "name": "Instalacoes_Realizadas",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fAdapter_atendimentos),",
              "    fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\"",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "986b4732-3b8e-439b-b1d6-feccb82fe988"
          },
          {
            "name": "Instalação_VisitaAgendada",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"VISITA_AGENDADA\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "df22667e-5004-47c5-b706-9b2c028f54a1"
          },
          {
            "name": "Instalação_Total",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\"",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "62ecebca-b6ca-4d8d-925c-93e4a956254e"
          },
          {
            "name": "Instalação_AguardandoAnalise",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"AGUARDANDO_ANALISE\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "735d73a0-4128-4999-9286-0778d55b0a69"
          },
          {
            "name": "Instalação_PosAtendimento",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"POS_ATENDIMENTO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e69f49e8-bed0-4054-a676-620c5d868005"
          },
          {
            "name": "Instalação_SemSolucao",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        ALL(fAdapter_atendimentos),  -- Remove todos os filtros aplicados à tabela adapter",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"SEM_SOLUCAO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0659831f-76a9-4db5-9869-37f8b9ca7bf1"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Instalação",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas Onboarding",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "ac9a1bf6-eea9-433d-86d6-5a1ea701f7c0",
        "measures": [
          {
            "name": "Onboarding_Solucionado",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"SOLUCIONADO\"},",
              "        fAdapter_atendimentos[Usuário Fechamento] IN {\"BIANCA NUNES COSTA \", \"ANA LUIZA SBAIS COSTA \", \"DANIELLE DA SILVA FIALHO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e9bf7ea0-85f9-4436-99b4-4b73e480b6e6"
          },
          {
            "name": "Onboarding_SemSolucao",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"SEM_SOLUCAO\"},",
              "        fAdapter_atendimentos[Usuário Fechamento] IN {\"BIANCA NUNES COSTA \", \"ANA LUIZA SBAIS COSTA \", \"DANIELLE DA SILVA FIALHO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "dbdf6ef8-5a22-4d7d-8b77-d42a91c20d4a"
          },
          {
            "name": "Onboarding_Realizados",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Usuário Fechamento] IN {\"BIANCA NUNES COSTA \", \"ANA LUIZA SBAIS COSTA \", \"DANIELLE DA SILVA FIALHO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1efb7271-f80c-4f06-8fdd-0859c5fd6012"
          },
          {
            "name": "Onboarding_Total",
            "expression": [
              "",
              "COALESCE(",
              "    CALCULATE(",
              "        COUNTROWS(fAdapter_atendimentos),",
              "        fAdapter_atendimentos[Tipo Atendimento] = \"ATIVAÇÃO\",",
              "        fAdapter_atendimentos[Status] IN {\"SOLUCIONADO\", \"SEM_SOLUCAO\"},",
              "        fAdapter_atendimentos[Usuário Fechamento] IN {\"BIANCA NUNES COSTA \", \"ANA LUIZA SBAIS COSTA \", \"DANIELLE DA SILVA FIALHO\"}",
              "    ),",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f1161606-69f3-49b6-ba50-da85066210da"
          },
          {
            "name": "% Onboarding Realizado",
            "expression": "DIVIDE([Onboarding_Realizados], [Onboarding_Total], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "37f332ce-68dd-4e51-8242-39f870712929"
          },
          {
            "name": "Total_Atendimentos_Onboarding",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fChat_relatorio_atendimento) + ",
              "    SUM(dCallflex_agente_consolidado[ENTRANTES_QTDE]) + ",
              "    SUM(dCallflex_agente_consolidado[SAINTES_QTDE]),",
              "    FILTER(",
              "        fChat_relatorio_atendimento, ",
              "        fChat_relatorio_atendimento[COLABORADOR] IN {\"BIANCA NUNES COSTA\", \"ANA LUIZA SBAIS COSTA\", \"DANIELLE DA SILVA FIALHO\"}",
              "    ),",
              "    FILTER(",
              "        dCallflex_agente_consolidado, ",
              "        dCallflex_agente_consolidado[COLABORADOR] IN {\"BIANCA NUNES COSTA\", \"ANA LUIZA SBAIS COSTA\", \"DANIELLE DA SILVA FIALHO\"}",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fa5780ab-fc14-4428-8e35-c3b0ebbaf2c9"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Onboarding",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fCallflex_chamadas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DATA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "876195ee-c708-4c18-a94b-ecd1130a8237",
            "sourceColumn": "DATA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_9bb371a8-6fc6-44ab-8fe7-fa1d41f0136f"
                },
                "isDefault": true,
                "relationship": "d9e3836d-934c-4052-a2a0-bd12855789b7"
              }
            ]
          },
          {
            "name": "FILA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "046e35c7-d289-4d95-a462-7ccc568a692a",
            "sourceColumn": "FILA",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8685e03-5ffe-4351-9eee-8fa92daa206f",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3537d6bd-5e01-4639-88aa-8ce31b9a9298",
            "sourceColumn": "ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "DESTINO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfa1c876-43e2-4bd8-a1f4-708e84c74b60",
            "sourceColumn": "DESTINO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f270090-a9fe-4263-856f-728bc7c90ffb",
            "sourceColumn": "TIPO",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "162733be-daaf-4b24-baa3-5a1b4928be84",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "DESLIGADOPOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0771167d-0f10-4647-932f-18854ecdf276",
            "sourceColumn": "DESLIGADOPOR",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_CONECTADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2395e46b-907a-4751-bf10-ae8822a82549",
            "sourceColumn": "TEMPO_CONECTADO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_DE_CONVERSACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "232a5ec4-3b06-410a-8fa9-7adfb3ba77a1",
            "sourceColumn": "TEMPO_DE_CONVERSACAO",
            "summarizeBy": "none"
          },
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b75e188e-1a2d-4d03-bc48-2280d9107b8c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Data (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3896ce5c-c842-4694-9ab4-97e27b29f3b6",
            "sourceColumn": "Data (ddmmaaaa)",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"fCallflex_chamadas\",\"TableItemName\":\"Hora (compartimentos)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn:ss",
            "lineageTag": "e0489543-b04d-43e7-8ba5-f2495646a155",
            "sourceColumn": "Hora",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_a384ac4e-028b-4e81-9215-5602139dc11c"
                },
                "isDefault": true,
                "relationship": "4c0811fe-7e9e-4273-8c5b-6b73189ee35c"
              }
            ]
          },
          {
            "name": "Hora (compartimentos)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"fCallflex_chamadas\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"Hora\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"Hora\"}},\"Size\":1.0,\"TimeUnit\":7}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('fCallflex_chamadas'[Hora]),",
              "\tBLANK(),",
              "\tINT('fCallflex_chamadas'[Hora] * 24) / 24",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 9,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "fCallflex_chamadas"
                          }
                        },
                        "Property": "Hora"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "Short Time",
            "lineageTag": "13a713b6-05c0-44b8-8160-8e29f7747a1a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "5e92d14a-281b-49fc-a36c-19a025d5af07",
        "partitions": [
          {
            "name": "fCallflex_chamadas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fCallflex_chamadas.csv\"),[Delimiter=\";\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "   ",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"6006-Artur Do Nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"6007-Maria Luiza De Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"6008-Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"6009-Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"6010-Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"6011-Cleison Rodrigues Da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"6012-Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"6013-Joao Vitor Da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"6014-Renan Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"6015-Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"6039-Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"6040-Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"6041-Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"6042-Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"6043-Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"6044-Rian Dos Santos Estevo\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"6045-Renan Duarte Marques De Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"6046-Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"6068-Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"6069-Danielle Da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"AGENTE\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"DANIELLE DA SILVA FIALHO\",{{\"DATA\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data (ddmmaaaa)\", each DateTime.Date([DATA]), type date),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Data Inserida\",{{\"AGENTE\", \"COLABORADOR\"}}),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Hora\", each DateTime.Time([DATA]), type time)",
                "in",
                "    #\"Hora Inserida\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCallflex_pausas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d778ea07-57b0-4be1-9a9e-696da745269b",
            "sourceColumn": "AGENTE",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f8fd498-0c03-47bc-b0a0-5875135d75b1",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_LOGADO_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04cc8f13-e383-46ae-94f9-8c31461156ab",
            "sourceColumn": "TEMPO_LOGADO_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_LOGADO_MEDIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aea868a9-0746-4dee-8d62-9ee3d57b3c14",
            "sourceColumn": "TEMPO_LOGADO_MEDIO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_PAUSADO_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2082eca-f41a-4c68-ab99-a392b3e63b77",
            "sourceColumn": "TEMPO_PAUSADO_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_PAUSADO_MEDIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ea67fdb-1a94-40b5-a967-f79e3010be76",
            "sourceColumn": "TEMPO_PAUSADO_MEDIO",
            "summarizeBy": "none"
          },
          {
            "name": "1-INDISPONIVEL-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ba1028d-0c54-4f87-a881-372ce42e4e97",
            "sourceColumn": "1-INDISPONIVEL-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "1-INDISPONIVEL-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c76fbd96-cc99-4803-8393-9624ca7e5b49",
            "sourceColumn": "1-INDISPONIVEL-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "2-PAUSA CAFE-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8543d51-0de1-4abe-bdf9-c0ac14449a8d",
            "sourceColumn": "2-PAUSA CAFE-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "2-PAUSA CAFE-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30e19bbe-19b1-49dd-99cb-0547d9046a7d",
            "sourceColumn": "2-PAUSA CAFE-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "3-PAUSA PESSOAL-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41cd9cde-71fd-46b2-80d5-0031f4b36b9b",
            "sourceColumn": "3-PAUSA PESSOAL-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "3-PAUSA PESSOAL-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3786687e-e507-4324-aca6-1a7af22d36ae",
            "sourceColumn": "3-PAUSA PESSOAL-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "4-PAUSA FEEDBACK-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "336a0f8e-903c-46bf-b0f0-ce6537da161e",
            "sourceColumn": "4-PAUSA FEEDBACK-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "4-PAUSA FEEDBACK-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b821a64-e81e-44a4-80f9-03df71f8ec87",
            "sourceColumn": "4-PAUSA FEEDBACK-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "7-PAUSA MANUTENCAO TI-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bd65958-8f09-4840-bc7f-b5977b9df376",
            "sourceColumn": "7-PAUSA MANUTENCAO TI-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "7-PAUSA MANUTENCAO TI-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "815b9af4-47dc-4f5a-851c-6da21049d585",
            "sourceColumn": "7-PAUSA MANUTENCAO TI-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "8-PAUSA ATENDIMENTO PRESENCIAL -TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a274069-3204-41a1-8532-b114445200d8",
            "sourceColumn": "8-PAUSA ATENDIMENTO PRESENCIAL -TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "8-PAUSA ATENDIMENTO PRESENCIAL -QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "418e7e4d-7ad8-45ff-889c-c0ac9e570761",
            "sourceColumn": "8-PAUSA ATENDIMENTO PRESENCIAL -QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "10-PAUSA BKOFFICE-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce29bee5-4d83-4553-913f-670352439e0b",
            "sourceColumn": "10-PAUSA BKOFFICE-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "10-PAUSA BKOFFICE-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "878d5332-bed3-43e0-9772-434865b0b504",
            "sourceColumn": "10-PAUSA BKOFFICE-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "12-PAUSA DE 15 MINUTOS-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccf80347-5bc7-4002-b2d1-8641bea252d3",
            "sourceColumn": "12-PAUSA DE 15 MINUTOS-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "12-PAUSA DE 15 MINUTOS-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8b4f94b-494d-45cd-8652-0438dafcf2eb",
            "sourceColumn": "12-PAUSA DE 15 MINUTOS-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "13-PAUSA ATENDIMENTO TECNICO-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ec155cf-01a5-41ca-95f0-f4819a1ceee8",
            "sourceColumn": "13-PAUSA ATENDIMENTO TECNICO-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "13-PAUSA ATENDIMENTO TECNICO-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f6e1f5a-e670-49ae-88ed-ada603dd41a3",
            "sourceColumn": "13-PAUSA ATENDIMENTO TECNICO-QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL-TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b02d2aeb-0128-4226-bc66-24aef6a5f8e1",
            "sourceColumn": "TOTAL-TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL-QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7b95eb9-cd3e-4dfb-ba06-4df6aa15677e",
            "sourceColumn": "TOTAL-QTDE",
            "summarizeBy": "sum"
          },
          {
            "name": "ADERENCIA_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dc7636a-e397-4f50-a506-af427862c904",
            "sourceColumn": "ADERENCIA_MEDIA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0dc7c274-a5fe-4bd1-975a-7eabd2931072",
        "partitions": [
          {
            "name": "dCallflex_pausas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/dCallflex_pausas.xlsx\"), null, true),",
                "    Export_Sheet = Fonte{[Item=\"Relatorio_pausas_agentes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"Artur Do Nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza De Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues Da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"Joao Vitor Da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian Dos Santos Estevo\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques De Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle Da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"DANIELLE DA SILVA FIALHO\",{{\"AGENTE_NOME\", \"COLABORADOR\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"TOTAL-QTDE\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"TOTAL-TEMPO\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"TEMPO_PAUSADO_TOTAL\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"TEMPO_PAUSADO_MEDIO\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído2\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"1-INDISPONIVEL-TEMPO\"}),",
                "    #\"Valor Substituído4\" = Table.ReplaceValue(#\"Valor Substituído3\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"2-PAUSA CAFE-TEMPO\"}),",
                "    #\"Valor Substituído5\" = Table.ReplaceValue(#\"Valor Substituído4\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"3-PAUSA PESSOAL-TEMPO\"}),",
                "    #\"Valor Substituído6\" = Table.ReplaceValue(#\"Valor Substituído5\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"4-PAUSA FEEDBACK-TEMPO\"}),",
                "    #\"Valor Substituído7\" = Table.ReplaceValue(#\"Valor Substituído6\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"7-PAUSA MANUTENCAO TI-TEMPO\"}),",
                "    #\"Valor Substituído8\" = Table.ReplaceValue(#\"Valor Substituído7\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"8-PAUSA ATENDIMENTO PRESENCIAL -TEMPO\"}),",
                "    #\"Valor Substituído9\" = Table.ReplaceValue(#\"Valor Substituído8\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"10-PAUSA BKOFFICE-TEMPO\"}),",
                "    #\"Valor Substituído10\" = Table.ReplaceValue(#\"Valor Substituído9\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"12-PAUSA DE 15 MINUTOS-TEMPO\"}),",
                "    #\"Valor Substituído11\" = Table.ReplaceValue(#\"Valor Substituído10\",\"---\",\"00:00:00\",Replacer.ReplaceValue,{\"13-PAUSA ATENDIMENTO TECNICO-TEMPO\"})",
                "in",
                "    #\"Valor Substituído11\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fCallflex_chamadas_agente_detalhado",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RAMAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5dbeb12-8915-4598-86ce-79361b7abb09",
            "sourceColumn": "RAMAL",
            "summarizeBy": "none"
          },
          {
            "name": "AGENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c2e7144-869c-46b9-bfd9-a7053254ffee",
            "sourceColumn": "AGENTE",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c29043d7-8fec-408b-b902-181f215af573",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "DATA_DE_LOGIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "22e332ea-4f8a-4484-9e39-e7540646fe2f",
            "sourceColumn": "DATA_DE_LOGIN",
            "summarizeBy": "none"
          },
          {
            "name": "HORA_DE_LOGIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1828878-ff5a-46ca-b5b1-f4b5cb068991",
            "sourceColumn": "HORA_DE_LOGIN",
            "summarizeBy": "none"
          },
          {
            "name": "FILAS_OBTIDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ed7d0f7-4f6a-4047-acc8-fe9bf74b8770",
            "sourceColumn": "FILAS_OBTIDAS",
            "summarizeBy": "none"
          },
          {
            "name": "LOGOFF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "422cc4ce-2507-45ca-8da4-f6f9c83ea781",
            "sourceColumn": "LOGOFF",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_EM_OPERACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb06e441-1573-4df8-8b36-06257e8103f0",
            "sourceColumn": "TEMPO_EM_OPERACAO",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_DISPONIVEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b88a077a-2af4-43cf-bffe-f265718da9e2",
            "sourceColumn": "TEMPO_DISPONIVEL",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL_CHAMADAS_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb341bd0-e19c-46e6-9e39-250fb9d295dc",
            "sourceColumn": "TOTAL_CHAMADAS_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL_CHAMADAS_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ccef73e-a1b2-4e37-9083-30dc345d5184",
            "sourceColumn": "TOTAL_CHAMADAS_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL_CHAMADAS_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f39e5b6-65c5-4f1b-92f5-6861ab9d2e2c",
            "sourceColumn": "TOTAL_CHAMADAS_MEDIA",
            "summarizeBy": "none"
          },
          {
            "name": "ENTRANTE_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ee18e65-f75b-40c1-ab2b-e741b93a46a3",
            "sourceColumn": "ENTRANTE_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "ENTRANTE_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc631691-a9b7-44e1-a36e-8d1be1f868a9",
            "sourceColumn": "ENTRANTE_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "ENTRANTE_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20695a0b-df7b-4949-9b43-4454cef6b741",
            "sourceColumn": "ENTRANTE_MEDIA",
            "summarizeBy": "none"
          },
          {
            "name": "SAINTE_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e763e4db-bd4f-4816-82cc-d0ef1d4bbd44",
            "sourceColumn": "SAINTE_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "SAINTE_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4959afd5-43ad-42dc-b2ce-8f34dd6fc81b",
            "sourceColumn": "SAINTE_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "SAINTE_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "774274b9-9df4-4cfc-a62d-61457d31254c",
            "sourceColumn": "SAINTE_MEDIA",
            "summarizeBy": "none"
          },
          {
            "name": "DISCADOR_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb46e4ec-abf0-4457-a5ee-30c2dde5a92f",
            "sourceColumn": "DISCADOR_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "DISCADOR_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2964a65a-79d5-408d-b891-5d1103d63a5c",
            "sourceColumn": "DISCADOR_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "DISCADOR_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2388bdf-32bb-4ed5-bd25-7bef37419147",
            "sourceColumn": "DISCADOR_MEDIA",
            "summarizeBy": "none"
          },
          {
            "name": "INTERNA_QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9838d715-e600-43da-b27d-b2ab6e7c2a88",
            "sourceColumn": "INTERNA_QTDE",
            "summarizeBy": "none"
          },
          {
            "name": "INTERNA_TEMPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60e37f78-17d8-43c6-b643-9176de9ad788",
            "sourceColumn": "INTERNA_TEMPO",
            "summarizeBy": "none"
          },
          {
            "name": "INTERNA_MEDIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1a60527-2216-4beb-9de2-140549018527",
            "sourceColumn": "INTERNA_MEDIA",
            "summarizeBy": "none"
          },
          {
            "name": "IGN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9305716a-ae20-4afd-8687-2ce6780b95da",
            "sourceColumn": "IGN",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_AFTERCALL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dec28dd3-ffb7-4f0a-ae10-c0dcc927861c",
            "sourceColumn": "TEMPO_AFTERCALL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "382c83aa-6854-4df4-a7a5-1af43447cfd1",
        "partitions": [
          {
            "name": "fCallflex_chamadas_agente_detalhado",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fCallflex_chamadas_agente_detalhado.xlsx\"), null, true),",
                "    Export_Sheet = Fonte{[Item=\"Relatorio_chamadas_agentes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"Artur Do Nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza De Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues Da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"Joao Vitor Da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian Dos Santos Estevo\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques De Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle Da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"DANIELLE DA SILVA FIALHO\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_DISPONIVEL\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"DATA_DE_LOGIN\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"AGENTE_NOME\", \"COLABORADOR\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fCallflex_pausas_detalhado",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71595cc0-0ac4-4509-84bb-4cc195f8e216",
            "sourceColumn": "AGENTE",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f78e9513-df35-4760-b2a9-c445b0ed9576",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "DATA_DE_LOGIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "64de2bc7-17d8-4cad-92bc-d2d5bc0cca13",
            "sourceColumn": "DATA_DE_LOGIN",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_d556f314-8bb0-42d9-9a44-f85e0726584a"
                },
                "isDefault": true,
                "relationship": "d72e0bd4-4f32-41d1-b950-40a61ac3f156"
              }
            ]
          },
          {
            "name": "LOGOFF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0f72407-d090-4ec3-84e6-471652351c60",
            "sourceColumn": "LOGOFF",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_TOTAL_LOGADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c740007-1e1f-4d29-a15a-ff123968f3d9",
            "sourceColumn": "TEMPO_TOTAL_LOGADO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_DE_PAUSA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66bbcff0-13c7-4a0a-a07a-cc2c8445bf77",
            "sourceColumn": "TIPO_DE_PAUSA",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPO_PAUSADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b277bb58-0c31-4ba9-b4ee-90830ebfd325",
            "sourceColumn": "TEMPO_PAUSADO",
            "summarizeBy": "none"
          },
          {
            "name": "INICIO_DA_PAUSA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0bb92fc-8f53-4570-a703-33a4c987b1a5",
            "sourceColumn": "INICIO_DA_PAUSA",
            "summarizeBy": "none"
          },
          {
            "name": "FIM_DA_PAUSA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "470566d3-5292-4cbf-b15d-fd8a98640027",
            "sourceColumn": "FIM_DA_PAUSA",
            "summarizeBy": "none"
          },
          {
            "name": "Data (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "059c9903-65d9-4b23-8d1c-12f259863fcb",
            "sourceColumn": "Data (ddmmaaaa)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "96022380-124a-4b4f-a2a6-6e603845ca9f",
        "partitions": [
          {
            "name": "fCallflex_pausas_detalhado",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fCallflex_pausas_detalhado.xlsx\"), null, true),",
                "    Export_Sheet = Fonte{[Item=\"Relatorio_pausas_agentes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Cabeçalhos Promovidos\",\"Artur Do Nascimento Arboleia\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"Maria Luiza De Souza Pereira\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"Wellington Dionizio Santos\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"Giovanni Quintino Da Silva\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"Fernando Alves Barbosa\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"Cleison Rodrigues Da Silva\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"Higor Vinicius Rodrigues Brito\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"Joao Vitor Da Silva Pimentel\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"Renan Luiz\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"Matheus Andrade De Araujo\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"Murilo Carlos Neponucena Nogueira\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"Adrean Felippe Mattos De Moura\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"Sabrina Padial\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"Vinicius Nunes Rodrigues\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"Esteban Gabriel Gardim Diaz\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"Rian Dos Santos Estevo\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"Renan Duarte Marques De Lima\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"Douglas Lisboa Silvano\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"Ana Luiza Sbais Costa\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"Bianca Nunes Costa\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"Danielle Da Silva Fialho\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"AGENTE_NOME\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"DANIELLE DA SILVA FIALHO\",\"---\",\"\",Replacer.ReplaceValue,{\"TEMPO_PAUSADO\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"DATA_DE_LOGIN\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data (ddmmaaaa)\", each DateTime.Date([DATA_DE_LOGIN]), type date),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Data Inserida\",{{\"AGENTE_NOME\", \"COLABORADOR\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "447d51ff65324eaf8fbc558346e852b9"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bd925a3e-fdb9-415b-ae09-839a733574ae",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_e16dbdbd-ac5e-44a7-9335-501005149e3c"
                },
                "isDefault": true,
                "relationship": "3fabf8dd-b414-4399-87ee-2e9a2b2f95f6"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('dCalendario'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0c2cac82-f3dd-4d34-824c-873fc592cb1f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('dCalendario'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f0bb25fe-a291-487f-a18d-8f19f59f96d5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Nome do mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('dCalendario'[Date],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "8d8a12f7-6ca7-47e4-ae1b-71b51df8fc66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTEr('dCalendario'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "942a1ec2-9fa4-4fc7-95af-b3ed41720c40",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY('dCalendario'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b22b477d-061a-404d-ba00-5655c8d592e9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Nome do dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('dCalendario'[Date],\"dddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "48360995-f4f2-454d-9f8a-bb7178a51f3b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia da semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY(dCalendario[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9b083650-0d40-45cb-985e-753223db5bde",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tipo de dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    WEEKDAY(dCalendario[Date], 2) >= 1 && WEEKDAY(dCalendario[Date], 2) <= 5, ",
              "    \"Dia útil\", ",
              "    \"Fim de semana\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "446c7a5e-32ad-4d73-9c96-95ffc9437122",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "37550d36-64a1-4063-8fcb-97437c75971a",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(2024, 1, 1), DATE(2024, 12, 31))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dColaboradores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Colaborador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e41eb921-bf5f-4109-ba79-a63078666bea",
            "sourceColumn": "Colaborador",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "adfcd62c-60ad-4c25-aaf1-3d2c6e16d11b",
        "partitions": [
          {
            "name": "dColaboradores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\hbrito\\OneDrive - Solução NetWork\\Documentos - Suporte Técnico\\Gestão\\Desempenho\\Dados\\dColaboradores.xlsx\"), null, true),",
                "    dColaboradores_Sheet = Fonte{[Item=\"dColaboradores\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dColaboradores_Sheet,{{\"Column1\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Colaborador\", type text}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7ad32777-930b-4009-b99b-c303ee716e4f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0d076529-b0ee-437f-a4ec-b9628db42016",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "72c4d3c0-4888-4cea-93b3-d93b95663a08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "79217429-5a5d-47be-b1d0-62eb77e8782f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "41b051d4-faf4-4285-a00d-7ac223e7ebe2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0cbf377f-62a1-4d1b-86df-0474a136167f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e14025f8-4f3e-401c-87e3-acbe75d98950",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "cd301bf6-a0fe-41eb-91d5-624523c5c9e2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f041ea2c-7560-4c6d-9bdb-11383945ac86",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9d6f6d97-4ce0-450e-97ec-98f6aca7f56d",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "ac939c0a-a1ca-4301-a85f-94b233d744d6",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "fa04f19f-db0f-41e9-bec3-4f3edd71ef0e",
                "ordinal": 3
              }
            ],
            "lineageTag": "ffa50c91-20f4-4c6a-9959-0d4743771f13"
          }
        ],
        "isHidden": true,
        "lineageTag": "d37e45f8-0a32-4098-a6cd-da3166e1c5bd",
        "partitions": [
          {
            "name": "LocalDateTable_7ad32777-930b-4009-b99b-c303ee716e4f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fChat_relatorio_resumo_usuarios'[Entrada])), 1, 1), Date(Year(MAX('fChat_relatorio_resumo_usuarios'[Entrada])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4968a8d5-4fba-4e64-8c8e-654f214cf655",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f140b23-c351-4523-8fa0-d31c593d123e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ee140243-fe7f-458f-9448-19264748092e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a195c25c-31d9-4a8b-b556-e525e1444853",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "74ce1a79-eb95-4efd-8d1e-c993f02d347d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dbaa596e-9058-4c56-a271-247a34b20a77",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1de99cf4-33bc-4657-8c50-b83dda018f7c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "85088c24-e0bb-427e-ab09-ed81285e8356",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6e3676a8-014d-43be-a2f5-2f724ba2c7c3",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "65df9048-306f-4207-ad03-20087cec4c8a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "7d625410-e809-42a5-84fb-dce2e910dd70",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "3857fe35-b75b-4a24-aeba-366d65bb5eef",
                "ordinal": 3
              }
            ],
            "lineageTag": "5e3c4d3e-40b5-4d8b-9d4a-2d04ebd180f7"
          }
        ],
        "isHidden": true,
        "lineageTag": "6dff2ac8-fa37-494d-9b71-8b372ec6c171",
        "partitions": [
          {
            "name": "LocalDateTable_4968a8d5-4fba-4e64-8c8e-654f214cf655",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fChat_relatorio_nps'[Data])), 1, 1), Date(Year(MAX('fChat_relatorio_nps'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9bb371a8-6fc6-44ab-8fe7-fa1d41f0136f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "21fd3188-f054-4d6c-b8ec-672f3d3cc9a8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "85db078a-a6f5-4ff3-9846-0f14295a39d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b263ae2c-427e-4080-9947-28ec379c0742",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d3c763da-c63c-4477-b271-56d4511897e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3d9a4322-8f7c-4dc8-8ff4-a5951ec82516",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "893322b8-39a3-4fc8-a41c-55a7680e11df",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "09eb8df2-5479-45d7-a0cb-54b897954e6d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "312c7627-07cc-4a00-a8b2-28e01635d957",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9520bc99-c228-41d0-ac0c-228dfa1d613e",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "605a81d3-585d-400a-a0ab-b4f4bf7e4a3d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "07e2a3f7-f11e-47a3-8e5a-1ddfc800c49a",
                "ordinal": 3
              }
            ],
            "lineageTag": "49130706-e605-42d3-8ca8-68da79537102"
          }
        ],
        "isHidden": true,
        "lineageTag": "e3ca4b5c-60b1-4336-8271-29ac3158fb84",
        "partitions": [
          {
            "name": "LocalDateTable_9bb371a8-6fc6-44ab-8fe7-fa1d41f0136f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fCallflex_chamadas'[DATA])), 1, 1), Date(Year(MAX('fCallflex_chamadas'[DATA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f91ec5c1-d982-4e68-aa2b-141ceaf68c32",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "67ad2205-7cad-486f-8b69-f07e67ce1b25",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4aba8f8a-ccd8-4d4a-b337-5c226d744af4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "88ee9eb8-35de-47ee-821d-0a08264c4443",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b1b77c0f-7a98-465e-a646-307ebb0a9cbe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "014d79e8-6f54-4bb1-829e-0e33c2d2e405",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "987eaadb-2251-4fa0-a13c-6b1d6b7001ae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "41c95df3-b6c3-45d4-8a9a-f5ca775462c5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "a753c999-f158-4894-a4c5-3c42b6db6ff0",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e53b19ec-747e-4635-9670-75046c8f8d2a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "6c52fa91-166c-4df8-be91-ec8731118f72",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "13341607-7c90-4adf-b448-dac32c36f725",
                "ordinal": 3
              }
            ],
            "lineageTag": "f41cd711-bc3a-40cc-8d34-f18c1a7ffe9a"
          }
        ],
        "isHidden": true,
        "lineageTag": "0cf2a196-4927-4552-9881-f0e945bba352",
        "partitions": [
          {
            "name": "LocalDateTable_f91ec5c1-d982-4e68-aa2b-141ceaf68c32",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fAdapter_reincidencias'[Data Abertura])), 1, 1), Date(Year(MAX('fAdapter_reincidencias'[Data Abertura])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "fAdapter_atendimentos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "QTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44b92d29-2f22-4115-abaf-01d9724a0a97",
            "sourceColumn": "QTD",
            "summarizeBy": "none"
          },
          {
            "name": "Protocolo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f105a93-9ff5-4e8d-b360-a9a1f6cc59f9",
            "sourceColumn": "Protocolo",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27a39bee-7439-4430-aae9-0771e664bef8",
            "sourceColumn": "Classificação Atendimento",
            "summarizeBy": "none"
          },
          {
            "name": "Data Abertura",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1508fa5a-254c-4f63-a5cb-b8326706cf1f",
            "sourceColumn": "Data Abertura",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_6bc8eb7d-071b-4eec-8af6-bdc7027e4e08"
                },
                "isDefault": true,
                "relationship": "5307732d-8821-4d32-80e8-7e4dd2fdbff7"
              }
            ]
          },
          {
            "name": "Data Fechamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6d7ea61-b3c0-4b26-b0c7-18580519dda4",
            "sourceColumn": "Data Fechamento",
            "summarizeBy": "none"
          },
          {
            "name": "TMA (em horas)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "696509db-d1f7-4701-8c1f-00720ac5575a",
            "sourceColumn": "TMA (em horas)",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afde0d56-df95-46fd-9afd-bd31df1bb44e",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Data Ativação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24b8c2d0-3ded-42b6-aebc-2617ab5ea01c",
            "sourceColumn": "Data Ativação",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75370aa8-f4d7-40b3-8af7-a17f94165997",
            "sourceColumn": "Tipo Atendimento",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Serviço",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e65e07d-000e-4b3a-a090-953865dca6cf",
            "sourceColumn": "Tipo Serviço",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24e1677c-039c-4129-bc0a-b032b8c02543",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "COLABORADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "370aa2ed-24f8-45f4-a12d-6c9c78171f42",
            "sourceColumn": "COLABORADOR",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "837b0089-a3bd-43bc-8c5a-b6b4d4f08c16",
            "sourceColumn": "Tipo Pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "Plano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "488572f0-8126-4ad8-b1ba-6f473a7dbd46",
            "sourceColumn": "Plano",
            "summarizeBy": "none"
          },
          {
            "name": "Gerou Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a55a3b4-9b51-4907-ae0f-1b98b168e4d2",
            "sourceColumn": "Gerou Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Dt/Hr Agend. Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c697ad13-c5af-4788-acef-86af40e51084",
            "sourceColumn": "Dt/Hr Agend. Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Dt/Hr. Inicio Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a95e4af7-9b6f-4e35-9326-6dc1078dc17b",
            "sourceColumn": "Dt/Hr. Inicio Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Dt/Hr. Fim Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09f9791f-5c64-46d3-b3fc-0fca868fc967",
            "sourceColumn": "Dt/Hr. Fim Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Técnico Visita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fcecbb5-7990-4ea1-8441-783d096763ae",
            "sourceColumn": "Técnico Visita",
            "summarizeBy": "none"
          },
          {
            "name": "Vencimento SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b241758-f17c-4876-84aa-bb656332d29e",
            "sourceColumn": "Vencimento SLA",
            "summarizeBy": "none"
          },
          {
            "name": "SLA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9026a52d-529a-4010-9d06-47d6af8a05b3",
            "sourceColumn": "SLA",
            "summarizeBy": "none"
          },
          {
            "name": "Motivo Fechamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "881ba342-6de7-4284-bee4-bd47f54c8c37",
            "sourceColumn": "Motivo Fechamento",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário Fechamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98de8df5-b03d-45a8-a02e-29dfb9935900",
            "sourceColumn": "Usuário Fechamento",
            "summarizeBy": "none"
          },
          {
            "name": "Reagendado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5bc7fbb-220f-4e0e-aff6-112474ca53ef",
            "sourceColumn": "Reagendado",
            "summarizeBy": "none"
          },
          {
            "name": "Data Reagendamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e08f79-d98c-47b8-8619-08cc246c3933",
            "sourceColumn": "Data Reagendamento",
            "summarizeBy": "none"
          },
          {
            "name": "Justificativa Reagendamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8e07a51-79e6-42f6-b052-deb4012483c3",
            "sourceColumn": "Justificativa Reagendamento",
            "summarizeBy": "none"
          },
          {
            "name": "Sinal Coletado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b70c9353-5710-46e0-a7dc-2ee696829e20",
            "sourceColumn": "Sinal Coletado",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a5f408b-8def-4dec-964b-5b8927699bf3",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Bairro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "794ff7de-7ad4-4b35-863d-a7322f8bce25",
            "sourceColumn": "Bairro",
            "summarizeBy": "none"
          },
          {
            "name": "Logradouro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40ceb9d7-ef62-4860-a364-e2843a75df45",
            "sourceColumn": "Logradouro",
            "summarizeBy": "none"
          },
          {
            "name": "Data Abertura (ddmmaaaa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dd5b1951-8bc1-42de-85b4-e7c414b3f0c3",
            "sourceColumn": "Data Abertura (ddmmaaaa)",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"LINK LOSS\", \"SEM CONEXÃO\", \"SEM CONEXÃO (ONU TRAVADA)\", \"PENDÊNCIAS TÉCNICOS\"}, \"Sem Conexão\",",
              "",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"SUPORTE TELEFONIA\", \"PENDÊNCIAS TELEFONIA\"}, \"Suporte Telefonia Fixa\",",
              "",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"SOLICITAÇÃO DE SUPORTE\", \"LENTIDÃO NA CONEXÃO\", \"SUPORTE VELOCIDADE CONTRATADA\", \"SUPORTE SEGUNDO PONTO\", \"SINAL ÓPTICO FORA DO PADRÃO (FIBRA ALTA)\"}, \"Suporte Conexão\",",
              "",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"PENDÊNCIAS SUPORTE - TELEFONIA MÓVEL\", \"SOLICITAÇÃO DE SUPORTE\"}, \"Suporte Telefonia Móvel\",",
              "",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"ADIAR VENCIMENTO DE FATURA\", \"PENDÊNCIAS COBRANÇA\", \"NEGOCIAÇÃO DE DÉBITO\", \"ALTERAÇÃO DA FORMA DE COBRANÇA\", \"ENVIO DE FATURA\", \"TROCA DE VENCIMENTO\", \"PENDÊNCIAS FINANCEIRO\", \"RECOLHER EQUIPAMENTO - SUSPENSÃO\", \"RETIRADA DE EQUIPAMENTO - INADIMPLENTE\", \"NEGATIVAÇÃO SERASA\"}, \"Financeiro\",",
              "    ",
              "    \"Outro\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "93a7fb00-0b4b-44bc-ab5e-a1466c806029",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Reincidencia Categoria Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR ClienteAtual = 'fAdapter_atendimentos'[Cliente]",
              "VAR GrupoAtual = 'fAdapter_atendimentos'[Categoria Atendimento]",
              "VAR DataAberturaAtual = 'fAdapter_atendimentos'[Data Abertura]",
              "",
              "-- Contar quantos atendimentos ocorreram antes da data atual para o cliente e tipo de atendimento",
              "VAR AtendimentosAnteriores =",
              "    COUNTROWS (",
              "        FILTER (",
              "            'fAdapter_atendimentos',",
              "            'fAdapter_atendimentos'[Cliente] = ClienteAtual &&",
              "            'fAdapter_atendimentos'[Categoria Atendimento] = GrupoAtual &&",
              "            'fAdapter_atendimentos'[Data Abertura] < DataAberturaAtual",
              "        )",
              "    )",
              "",
              "-- Retornar se é reincidente ou não",
              "RETURN",
              "    IF(AtendimentosAnteriores > 0, 1, 0)",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f777a158-c41a-4981-976d-bbe883ab3ecd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Setor Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"LINK LOSS\", \"SEM CONEXÃO\", \"SEM CONEXÃO (ONU TRAVADA)\", \"PENDÊNCIAS TÉCNICOS\", \"SUPORTE TELEFONIA\", \"PENDÊNCIAS TELEFONIA\", \"SOLICITAÇÃO DE SUPORTE\", \"LENTIDÃO NA CONEXÃO\", \"SUPORTE VELOCIDADE CONTRATADA\", \"SUPORTE SEGUNDO PONTO\", \"PENDÊNCIAS SUPORTE - TELEFONIA MÓVEL\", \"SOLICITAÇÃO DE SUPORTE\"}, \"Suporte\",",
              "",
              "    'fAdapter_atendimentos'[Tipo Atendimento] IN {\"ADIAR VENCIMENTO DE FATURA\", \"PENDÊNCIAS COBRANÇA\", \"NEGOCIAÇÃO DE DÉBITO\", \"ALTERAÇÃO DA FORMA DE COBRANÇA\", \"ENVIO DE FATURA\", \"TROCA DE VENCIMENTO\", \"PENDÊNCIAS FINANCEIRO\", \"RECOLHER EQUIPAMENTO - SUSPENSÃO\", \"RETIRADA DE EQUIPAMENTO - INADIMPLENTE\", \"NEGATIVAÇÃO SERASA\"}, \"Financeiro\",",
              "    ",
              "    \"Outro\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d3b1e961-b9a2-456b-b424-48e399bafcbc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Reincidencia Setor Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR ClienteAtual = 'fAdapter_atendimentos'[Cliente]",
              "VAR GrupoAtual = 'fAdapter_atendimentos'[Setor Atendimento]",
              "VAR DataAberturaAtual = 'fAdapter_atendimentos'[Data Abertura]",
              "",
              "-- Contar quantos atendimentos ocorreram antes da data atual para o cliente e tipo de atendimento",
              "VAR AtendimentosAnteriores =",
              "    COUNTROWS (",
              "        FILTER (",
              "            'fAdapter_atendimentos',",
              "            'fAdapter_atendimentos'[Cliente] = ClienteAtual &&",
              "            'fAdapter_atendimentos'[Setor Atendimento] = GrupoAtual &&",
              "            'fAdapter_atendimentos'[Data Abertura] < DataAberturaAtual",
              "        )",
              "    )",
              "",
              "-- Retornar se é reincidente ou não",
              "RETURN",
              "    IF(AtendimentosAnteriores > 0, 1, 0)",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c29496ef-eee0-4096-9cea-58a22ea5932c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Reincidencia Tipo Atendimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR ClienteAtual = 'fAdapter_atendimentos'[Cliente]",
              "VAR GrupoAtual = 'fAdapter_atendimentos'[Tipo Atendimento]",
              "VAR DataAberturaAtual = 'fAdapter_atendimentos'[Data Abertura]",
              "",
              "-- Contar quantos atendimentos ocorreram antes da data atual para o cliente e tipo de atendimento",
              "VAR AtendimentosAnteriores =",
              "    COUNTROWS (",
              "        FILTER (",
              "            'fAdapter_atendimentos',",
              "            'fAdapter_atendimentos'[Cliente] = ClienteAtual &&",
              "            'fAdapter_atendimentos'[Tipo Atendimento] = GrupoAtual &&",
              "            'fAdapter_atendimentos'[Data Abertura] < DataAberturaAtual",
              "        )",
              "    )",
              "",
              "-- Retornar se é reincidente ou não",
              "RETURN",
              "    IF(AtendimentosAnteriores > 0, 1, 0)",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "83240ed1-bea7-4e5e-b687-36c3c3e35ecb",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Reincidencia Geral",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR ClienteAtual = 'fAdapter_atendimentos'[Cliente]",
              "VAR DataAberturaAtual = 'fAdapter_atendimentos'[Data Abertura]",
              "",
              "-- Contar quantos atendimentos ocorreram antes da data atual para o cliente e tipo de atendimento",
              "VAR AtendimentosAnteriores =",
              "    COUNTROWS (",
              "        FILTER (",
              "            'fAdapter_atendimentos',",
              "            'fAdapter_atendimentos'[Cliente] = ClienteAtual &&",
              "            'fAdapter_atendimentos'[Data Abertura] < DataAberturaAtual",
              "        )",
              "    )",
              "",
              "-- Retornar se é reincidente ou não",
              "RETURN",
              "    IF(AtendimentosAnteriores > 0, 1, 0)",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6232b077-9b67-4eaa-babf-5099a1aa1971",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "cd6ab9fa-02a6-4eab-8f95-01e26a318d6f",
        "partitions": [
          {
            "name": "fAdapter_atendimentos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/fAdapter_atendimentos.xlsx\"), null, true),",
                "    Export_Sheet = Fonte{[Item=\"Export\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Cabeçalhos Promovidos\", \"Data Abertura (ddmmaaaa)\", each DateTime.Date([Data Abertura]), type date),",
                "    #\"ARTUR DO NASCIMENTO ARBOLEIA\" = Table.ReplaceValue(#\"Data Inserida\",\"ARTUR DO NASCIMENTO ARBOLEIA\",\"ARTUR DO NASCIMENTO ARBOLEIA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MARIA LUIZA DE SOUZA PEREIRA\" = Table.ReplaceValue(#\"ARTUR DO NASCIMENTO ARBOLEIA\",\"MARIA LUIZA DE SOUZA PEREIRA\",\"MARIA LUIZA DE SOUZA PEREIRA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"WELLINGTON DIONIZIO SANTOS\" = Table.ReplaceValue(#\"MARIA LUIZA DE SOUZA PEREIRA\",\"WELLINGTON DIONIZIO SANTOS\",\"WELLINGTON DIONIZIO SANTOS\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"GIOVANNI QUINTINO DA SILVA\" = Table.ReplaceValue(#\"WELLINGTON DIONIZIO SANTOS\",\"GIOVANNI QUINTINO DA SILVA\",\"GIOVANNI QUINTINO DA SILVA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"FERNANDO ALVES BARBOSA\" = Table.ReplaceValue(#\"GIOVANNI QUINTINO DA SILVA\",\"FERNANDO ALVES BARBOSA\",\"FERNANDO ALVES BARBOSA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"CLEISON RODRIGUES DA SILVA\" = Table.ReplaceValue(#\"FERNANDO ALVES BARBOSA\",\"CLEISON RODRIGUES DA SILVA\",\"CLEISON RODRIGUES DA SILVA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"HIGOR VINICIUS RODRIGUES BRITO\" = Table.ReplaceValue(#\"CLEISON RODRIGUES DA SILVA\",\"HIGOR VINICIUS RODRIGUES BRITO\",\"HIGOR VINICIUS RODRIGUES BRITO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"JOAO VITOR DA SILVA PIMENTEL\" = Table.ReplaceValue(#\"HIGOR VINICIUS RODRIGUES BRITO\",\"JOÃO VITOR DA SILVA PIMENTEL\",\"JOAO VITOR DA SILVA PIMENTEL\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RENAN LUIZ\" = Table.ReplaceValue(#\"JOAO VITOR DA SILVA PIMENTEL\",\"RENAN LUIZ GONDO DA SILVA\",\"RENAN LUIZ\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MATHEUS ANDRADE DE ARAUJO\" = Table.ReplaceValue(#\"RENAN LUIZ\",\"MATHEUS ANDRADE DE ARAUJO\",\"MATHEUS ANDRADE DE ARAUJO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"MURILO CARLOS NEPONUCENA NOGUEIRA\" = Table.ReplaceValue(#\"MATHEUS ANDRADE DE ARAUJO\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"MURILO CARLOS NEPONUCENA NOGUEIRA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ADREAN FELIPPE MATTOS DE MOURA\" = Table.ReplaceValue(#\"MURILO CARLOS NEPONUCENA NOGUEIRA\",\"ADREAN FELIPPE MATTOS DE MOURA\",\"ADREAN FELIPPE MATTOS DE MOURA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"SABRINA PADIAL\" = Table.ReplaceValue(#\"ADREAN FELIPPE MATTOS DE MOURA\",\"SABRINA PADIAL\",\"SABRINA PADIAL\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"VINICIUS NUNES RODRIGUES\" = Table.ReplaceValue(#\"SABRINA PADIAL\",\"VINICIUS NUNES RODRIGUES\",\"VINICIUS NUNES RODRIGUES\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ESTEBAN GABRIEL GARDIM DIAZ\" = Table.ReplaceValue(#\"VINICIUS NUNES RODRIGUES\",\"ESTEBAN GABRIEL GARDIM DIAZ\",\"ESTEBAN GABRIEL GARDIM DIAZ\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RIAN DOS SANTOS ESTEVO\" = Table.ReplaceValue(#\"ESTEBAN GABRIEL GARDIM DIAZ\",\"RIAN DOS SANTOS ESTEVO\",\"RIAN DOS SANTOS ESTEVO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"RENAN DUARTE MARQUES DE LIMA\" = Table.ReplaceValue(#\"RIAN DOS SANTOS ESTEVO\",\"RENAN DUARTE MARQUES DE LIMA\",\"RENAN DUARTE MARQUES DE LIMA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"DOUGLAS LISBOA SILVANO\" = Table.ReplaceValue(#\"RENAN DUARTE MARQUES DE LIMA\",\"DOUGLAS LISBOA SILVANO\",\"DOUGLAS LISBOA SILVANO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"ANA LUIZA SBAIS COSTA\" = Table.ReplaceValue(#\"DOUGLAS LISBOA SILVANO\",\"ANA LUIZA SBAIS COSTA\",\"ANA LUIZA SBAIS COSTA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"BIANCA NUNES COSTA\" = Table.ReplaceValue(#\"ANA LUIZA SBAIS COSTA\",\"BIANCA NUNES COSTA\",\"BIANCA NUNES COSTA\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"DANIELLE DA SILVA FIALHO\" = Table.ReplaceValue(#\"BIANCA NUNES COSTA\",\"DANIELLE DA SILVA FIALHO\",\"DANIELLE DA SILVA FIALHO\",Replacer.ReplaceValue,{\"Usuário Abertura\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"DANIELLE DA SILVA FIALHO\",{{\"Usuário Abertura\", \"COLABORADOR\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"Data Abertura\", type datetime}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each ([QTD] = 1))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d556f314-8bb0-42d9-9a44-f85e0726584a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4f7d1979-a6f5-412a-87cd-aaf769e38321",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9bdc3e79-0bc0-4740-9c4a-84a12623d30d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "cafd45ad-488b-489f-8e4b-5322d6a6d9f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6bf43a72-6416-45a1-adeb-5b20b6443517",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "85b89745-945d-4883-93dc-2b67df7cd0b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "af0f8cc2-314e-40ff-a582-98c87334dd55",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6baef576-03b3-40ee-b67d-6e7a204c4ee7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f174ac37-dc35-4393-be25-c9564fa222e6",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d7488246-f47f-490f-8093-e0682378f1e1",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "9de55d08-27db-4715-9d4d-ff379fde7601",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "63b280ca-3094-4aa6-bf6c-4e92a805a5f0",
                "ordinal": 3
              }
            ],
            "lineageTag": "307628d2-9646-4c0d-b631-b2f07e09cdf2"
          }
        ],
        "isHidden": true,
        "lineageTag": "8361b82f-1dd7-454b-936d-64a830747fd1",
        "partitions": [
          {
            "name": "LocalDateTable_d556f314-8bb0-42d9-9a44-f85e0726584a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fCallflex_pausas_detalhado'[DATA_DE_LOGIN])), 1, 1), Date(Year(MAX('fCallflex_pausas_detalhado'[DATA_DE_LOGIN])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_402833ec-6b08-4a3c-9ab5-3bee6ab4a591",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1ff3d3f9-4c62-4cad-a478-636ede616163",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d5c7cf86-272b-48b9-aeb4-182b17867101",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4722606c-4170-4e36-be8e-48120e4f0cc5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3046a8b3-45a2-4290-8147-90f5162abefe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "76e9ec9c-713b-49ff-982a-a9a9e84d0572",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "99dfc4c2-aa1f-4d0a-8176-fc3a77b22e44",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6ed68577-f1f6-4520-9671-23e3df952349",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "95ab5e00-eb40-4942-9015-9fc5b9261a90",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "35d706a4-8456-42c3-be1e-3565d2cac4e0",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "d9b3bfe9-1b6f-42a7-a7ca-c454861d04bf",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "1ee1ba0e-d71b-4e01-95e6-b051463b0706",
                "ordinal": 3
              }
            ],
            "lineageTag": "babac0de-e683-412b-a9fc-b57a7b8a6363"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a65a0d7-cc74-49bb-91a1-1da07e86339f",
        "partitions": [
          {
            "name": "LocalDateTable_402833ec-6b08-4a3c-9ab5-3bee6ab4a591",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fChat_relatorio_atendimento'[Data de entrada])), 1, 1), Date(Year(MAX('fChat_relatorio_atendimento'[Data de entrada])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a384ac4e-028b-4e81-9215-5602139dc11c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4ea24499-3da9-418d-b0bc-230f68c16348",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "463fc471-5240-46ae-9ba1-3f3a53cfc2df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b811ec87-e73c-4046-ac31-bd364de3987d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7eec2187-dd0d-497c-b122-29bd8f55fb31",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "86efa72c-afeb-41f5-8f02-35fc493ac4ea",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "391eafaf-9e15-4db1-b538-099a5b4ef5ce",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c3ba7c25-5af4-48d0-a12d-fae5c0478914",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f14dcb53-5d5c-4144-a8e8-2156e47ef7bb",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d8af35db-4808-49b5-801e-3fcb189fed8f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "02a3f194-c04d-4b06-83c1-999fed4e21b2",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8289a29b-c7a7-4982-8d4b-73a8deb958ab",
                "ordinal": 3
              }
            ],
            "lineageTag": "5b4540db-39b2-47d7-b8db-f618521d4959"
          }
        ],
        "isHidden": true,
        "lineageTag": "e11a21aa-8532-41da-bf51-d32f6d8cf7f5",
        "partitions": [
          {
            "name": "LocalDateTable_a384ac4e-028b-4e81-9215-5602139dc11c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fCallflex_chamadas'[Hora])), 1, 1), Date(Year(MAX('fCallflex_chamadas'[Hora])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dHoras",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Horas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Time",
            "lineageTag": "b6f02e41-5ac4-4e16-9512-379f03d037aa",
            "sourceColumn": "Horas",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c401e4f-fbcc-4dfb-b75c-277a82e05a6a",
        "partitions": [
          {
            "name": "dHoras",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://solucaonet.sharepoint.com/sites/suportecs/Documentos%20Compartilhados/Gest%C3%A3o/Desempenho/Dados/dHoras.xlsx\"), null, true),",
                "    dHoras_Sheet = Fonte{[Item=\"dHoras\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(dHoras_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Horas\", type datetime}}),",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(#\"Tipo Alterado\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas em Branco Removidas\",{{\"Horas\", type time}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e16dbdbd-ac5e-44a7-9335-501005149e3c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed6ce68d-33fa-4cd7-b23a-840fa25c4b10",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "47550db6-5484-40c2-a674-743b9713b963",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b2732826-9265-4a14-8503-35fc1885e427",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a2302a38-61b7-4a91-b087-1d49ed779fe3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f092d3b2-c419-4042-a991-3f25cba80dc5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2e04ed07-4faa-4946-ba9f-00e1ca269c4f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b1afbc10-9833-4d82-960c-cbef96f200f7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "34ba3814-e429-4f5d-88e1-7b4f46a40623",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a1596279-5d99-41e0-948f-dcfa579d64f9",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b45489eb-5644-447a-9bbb-214b822009de",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "04711cb2-4d63-4ac8-9f45-85336cf9f486",
                "ordinal": 3
              }
            ],
            "lineageTag": "0743d62e-1434-4feb-864b-492629b9c935"
          }
        ],
        "isHidden": true,
        "lineageTag": "7696e009-f23c-4016-882e-d78b454e7d80",
        "partitions": [
          {
            "name": "LocalDateTable_e16dbdbd-ac5e-44a7-9335-501005149e3c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Medidas Reincidencia",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "e003f24b-c8db-4023-84a9-00e05487d8fc",
        "measures": [
          {
            "name": "Reincidencia Categoria",
            "expression": [
              "",
              "VAR ClienteAtual = MAX('fAdapter_atendimentos'[Cliente])  -- Valor do Cliente no contexto atual",
              "VAR GrupoAtual = MAX('fAdapter_atendimentos'[Categoria Atendimento])  -- Valor do Grupo de Atendimento no contexto atual",
              "",
              "-- Encontrar a quantidade de atendimentos do cliente no grupo de atendimento",
              "VAR QtdAtendimentos =",
              "    CALCULATE (",
              "        COUNTROWS('fAdapter_atendimentos'),  -- Conta o número de atendimentos",
              "        FILTER (",
              "            ALLSELECTED('fAdapter_atendimentos'),  -- Considera os filtros aplicados no contexto (exceto o filtro de 'Data Abertura')",
              "            'fAdapter_atendimentos'[Cliente] = ClienteAtual &&  -- Filtro para o cliente atual",
              "            'fAdapter_atendimentos'[Categoria Atendimento] = GrupoAtual  -- Filtro para o grupo de atendimento atual",
              "        )",
              "    )",
              "",
              "-- Caso o cliente tenha apenas um atendimento no grupo, ele não será reincidente",
              "VAR Reincidente = ",
              "    IF (",
              "        QtdAtendimentos > 1,  -- Se houver mais de 1 atendimento",
              "        IF (",
              "            MIN('fAdapter_atendimentos'[Data Abertura]) = ",
              "                CALCULATE (",
              "                    MIN('fAdapter_atendimentos'[Data Abertura]),  -- Obtém a menor data de abertura",
              "                    FILTER (",
              "                        ALLSELECTED('fAdapter_atendimentos'),  -- Considera os filtros aplicados",
              "                        'fAdapter_atendimentos'[Cliente] = ClienteAtual &&  -- Filtro para o cliente atual",
              "                        'fAdapter_atendimentos'[Categoria Atendimento] = GrupoAtual  -- Filtro para o grupo de atendimento atual",
              "                    )",
              "                ), ",
              "            1,  -- Marca como reincidente",
              "            0   -- Caso contrário, não é reincidente",
              "        ),",
              "        0   -- Se houver apenas 1 atendimento, marca como não reincidente",
              "    )",
              "",
              "RETURN ",
              "    Reincidente",
              ""
            ],
            "formatString": "0",
            "lineageTag": "56f04fa9-94b5-4585-8da1-0c8e5f26ce49"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Reincidencia",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6bc8eb7d-071b-4eec-8af6-bdc7027e4e08",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fdbb7153-e6f1-4640-b645-db80045e9473",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e428b13d-e522-43c4-bbff-5edab6472a9a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "01d67f55-051c-4476-9215-503040e51dc4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "14a8020c-01e0-408a-929a-2082a1b8b9bc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "852a5468-a1b0-457a-a44b-95d766fe579c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9955c4ad-ce2f-4165-9470-23a4a51a864d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8a0df35a-4fd5-4402-9881-64f7e9c8e2a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "075431f9-1cec-4d0a-b541-70d4ab75e6a5",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e9aca0c5-aba8-4677-a351-38cbcc5eef56",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "4d580ee9-58e9-4e23-a7ef-bf1386918a56",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "bc40c5e1-250f-4b41-ae12-6da301a52e68",
                "ordinal": 3
              }
            ],
            "lineageTag": "7f2b7f73-47f4-45f2-9995-13ab845efce8"
          }
        ],
        "isHidden": true,
        "lineageTag": "f5778f54-0bbc-4e3d-ac77-96cc45eeb6c6",
        "partitions": [
          {
            "name": "LocalDateTable_6bc8eb7d-071b-4eec-8af6-bdc7027e4e08",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fAdapter_atendimentos'[Data Abertura])), 1, 1), Date(Year(MAX('fAdapter_atendimentos'[Data Abertura])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}